### ISSUE TITLE
Exception when trying to use Call.BeginTalk

### ISSUE THREAD

**Issue by hfadeelw** [Nexmo/nexmo-dotnet#100]
I initiate a call, then do BeginTalk but I 'm getting the following error:
Note: the call is being made and I hair what I wrong in the Json file but BeginTalk always fail.

![image](https://user-images.githubusercontent.com/40150961/42655281-7ee73420-85d0-11e8-8618-ff44aed89eb6.png)

**Comment by slorello89** [comment]
#187 will make the errors more explicit - you're most likely encountering an HTTP error when you try to send the request - guess would be it's a 401 (bad credentials) I'd refresh your private key - ensure it's saved and try it again.

**Comment by slorello89** [comment]
Hello - as of v5.0.0 - this should no longer be an issue - the SDK when encountering a problem with throw a much more explicit error that will point you at exactly what went wrong - I'm going to close this issue because of this - if you continue to encounter this issue feel free to reopen.
