### ISSUE TITLE
sendTask.Result.StatusCode evaluated as NotFound

### ISSUE THREAD

**Issue by ChrisGuzman** [Nexmo/nexmo-dotnet#102]
This issue created on behalf of a developer trying out our Stitch API. It looks like there's an issue when creating a user. 

I believe the Stitch API made some breaking changes after the rc1 release was cut. I'm in the process of finding out what changes were made.

> for the new .net lib:
 on failed request the sdk is failing to give detailed info to the developer
![usercreationerror](https://user-images.githubusercontent.com/1993855/43266201-61bb6bec-90b0-11e8-9b67-0ebedc9080ba.png)
![dorequestmethod_error](https://user-images.githubusercontent.com/1993855/43266204-62fadcf4-90b0-11e8-8a78-4d4f87b4b020.png)

**Comment by smithrobs** [comment]
Addressed in v3.1.0-rc2. Thanks!
