### ISSUE TITLE
Getting Error Message: "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by Benjamin1973** [Nexmo/nexmo-dotnet#105]
### General description of the issue or question
Using the C# client.  Not sure exactly which Framework, but it's not .NET Core for sure.

I haven't changed any code, and I've checked that I have a remaining balance.  It has started today (August 22).

### Version or commit hash
I'm not sure.  When I open the .dll, it just says version 1.0
 
### Expected Behavior
It should have sent an SMS to my customers instead of crashing.

### Actual Behavior
SMS.SMSResponse Response = SMS.Send(SMSR); //my code line

Returns the message 

[Socket Exception (0x2746): An existing connection was forcibly closed by the remote host.]

**Comment by smithrobs** [comment]
You are likely encountering Nexmo's August 21, 10:00 BST [permanent shutdown of TLSv1 and TLSv1.1](https://www.nexmo.com/blog/2018/08/09/additional-grace-period-legacy-tls-protocols/).

Please review that information and make changes to your systems as required. Feel free to [file a support request](https://help.nexmo.com/hc/en-us/requests/new) with Nexmo for additional support.

**Comment by Benjamin1973** [comment]
Ok, that's really great news.  I had no idea about the changeover.



________________________________
