### ISSUE TITLE
Nexmo System.Net.Sockets.SocketException Exception

### ISSUE THREAD

**Issue by srujanaj** [Nexmo/nexmo-dotnet#107]
Implemented outbound SMS notification using Nexmo API. It was working fine a few days back and suddenly stopped working. When I debugged the code, I am getting System.Net.Sockets.SocketException and system.ObjectDisposedException

 .NET Framework 4.5.2

Nexmo-API version: 3.0.1

        

var creds = new Nexmo.Api.Request.Credentials
                    {
                        ApiKey = NEXMO_API_KEY,
                        ApiSecret = NEXMO_API_SECRET

                    };
                    var results = SMS.Send(new SMS.SMSRequest
                    {
                        from = fromno,
                        to = to,
                        text = text
                    }, creds);

**Comment by smithrobs** [comment]
@srujanaj You are likely encountering Nexmo's August 21, 10:00 BST [permanent shutdown of TLSv1 and TLSv1.1](https://www.nexmo.com/blog/2018/08/09/additional-grace-period-legacy-tls-protocols/).

Please review that information and make changes to your systems as required. Feel free to [file a support request](https://help.nexmo.com/hc/en-us/requests/new) with Nexmo for additional support.
