### ISSUE TITLE
Nexmo CSharp Client not working with newly created phone number

### ISSUE THREAD

**Issue by mjmcginty** [Nexmo/nexmo-dotnet#108]
Framework targeted: .NET 4.6.2
Nexmo CSharp Client version: 3.0.1.0
O/S: Win 7, Windows Server 2012

My code, which had been working for 8 months or so, created an SMSRequest object, then called the static Send method in the Nexmo.Api.SMS namespace (which implicitly loaded credentials from Web.config.)

var req = new Nexmo.Api.SMS.SMSRequest
{
    from = Properties.Settings.Default.FromNumber_Nexmo,
    to = phoneNumber,
    text = message
};
var result = Nexmo.Api.SMS.Send(req);

Life was good.

I accidentally let my account run out of money, and my number went away.  After creating a new one, and updating my settings, that code no longer worked, the innermost exception message is "An existing connection was forcibly closed by the remote host"

I saw on your site there was an SDK update and different sample source, so I updated using nuget, and tried the new source:

// same SMSRequest creation
var creds = new Nexmo.Api.Request.Credentials(
    Properties.Settings.Default.Nexmo_ApiKey, 
    Properties.Settings.Default.Nexmo_ApiSecret);
var client = new Nexmo.Api.Client(creds);
var results = client.SMS.Send(req);

Same exception.

The Nexmo support person pointed out that the code on your site looked different, obviously it is functionally the same but to humor him...

results = client.SMS.Send(new Nexmo.Api.SMS.SMSRequest
{
    from = Properties.Settings.Default.FromNumber_Nexmo,
    to = phoneNumber,
    text = message
});

Doesn't freaking work!  Same exception.  I know my number and creds work, I am able to use the Node.js CLI successfully, I can even successfully send an SMS using jQuery ajax, to call your Web API.  Both of those work fine but are impractical from my C# web app

Any of the source fragments above should work, correct?  I was told that your security requirements have recently changed, the minimum version of TLS is now 2.0.  Were previously existing numbers grandfathered into the old requirement?  Is C# client 3.0.1 compliant with new requirements?

TIA for any light you may be able to shed.

-MM

**Comment by RabebOthmani** [comment]
Hi @mjmcginty ,
I'm about to build a function in the Client Library to check the TLS version. 
Meanwhile, you could make a http request to the following url  https://api.nexmo.com/tlsverification from your application to verify the TLS version, it should return a 200Ok if it supports 1.2 and 400 if not.

**Comment by mjmcginty** [comment]
Actually it resets the connection as well, seems like it's being enforced by a firewall?  However I did determine the TLS version using Wireshark, and it is using TLSv1, not 1.2.  My app targets .NET framework version 4.6.2, how do I make it use TLSv1.2?

**Comment by mjmcginty** [comment]
To answer my own question:

using System.Net;
...

ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
