### ISSUE TITLE
Getting a 401 error, help with auth

### ISSUE THREAD

**Issue by HStuart18** [Nexmo/nexmo-dotnet#109]
Hi there,

When trying to run:

`var result = client.Call.BeginTalk(uuid, new Nexmo.Api.Voice.Call.TalkCommand
            {
                text = "This test finally worked well done!",
                voice_name = "Kimberly"
            });`

I am getting:

`Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2018-09-01T02:36:38.5911745Z","tags":{"ai.internal.nodeName":"LAPTOP-8AJ9T8A6","ai.operation.name":"GET Call/Index","ai.operation.id":"54034fcc-4ff4ea449fefcbef","ai.application.ver":"1.0.0.0","ai.location.ip":"119.81.44.3","ai.internal.sdkVersion":"rdddsc:2.4.1-1362","ai.cloud.roleInstance":"LAPTOP-8AJ9T8A6","ai.operation.parentId":"|54034fcc-4ff4ea449fefcbef."},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"PUT /v1/calls/d8cb7b6775f05a8d166002603bac17cf/talk","id":"|54034fcc-4ff4ea449fefcbef.1.","data":"https://api.nexmo.com/v1/calls/d8cb7b6775f05a8d166002603bac17cf/talk","duration":"00:00:00.6299447","resultCode":"401","success":false,"type":"Http","target":"api.nexmo.com","properties":{"AspNetCoreEnvironment":"Development","DeveloperMode":"true"}}}}`

Noting the resultCode 401, meaning the request is unauthorised. I am setting my credentials with:

`Credentials credentials = new Credentials(nexmoApiKey: "18........a", nexmoApiSecret: "t1q........zX", nexmoApplicationId: "5f01ae7..........7bb6503e", nexmoApplicationPrivateKey: Resource.privatekey);`

My private key resource pretyy much has the name "privatekey" and then its value is the actual key (me copying and pasting the contents from the downloaded .key file). How can I fix this?

**Comment by RabebOthmani** [comment]
Closing the issue here since Harry and I are working on this via email
