### ISSUE TITLE
Implement Secret Management API

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-dotnet#114]
We have a new API for managing account secrets, fully documented here: https://nexmo-developer-staging-pr-579.herokuapp.com/api/account/secret-management

It consists of 4 endpoints to be added to the existing `account` namespace:

- `listSecrets(apiKey)` - List the secrets associated with the provided api key.
- `getSecret(apiKey, secretId)` - Obtain the details of the secret identified by the provided secret ID.
- `createSecret(apiKey, newSecret)`  - Create a secret with the details provided in new secret.
- `deleteSecret(apiKey, secretId)` - Delete the secret associated with the provided secret ID.

(Please note that the parameter is called `account_id` in the documentation, but _should_ be called `api_key` as seen here.)

**Comment by RabebOthmani** [comment]
FYI @judy2k , I'm closing this issue. The implementation is done. 
https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/ApiSecret.cs
