### ISSUE TITLE
Please release new version for NumberInsight API!!!

### ISSUE THREAD

**Issue by gaupoit** [Nexmo/nexmo-dotnet#12]

**Comment by smithrobs** [comment]
You are in luck! We just released a [pre-release version 2.0.0-rc1](https://www.nuget.org/packages/Nexmo.Csharp.Client/2.0.0-rc1) to NuGet that supports the NumberInsight API. An official 2.0 release will come within a week or so.

**Comment by smithrobs** [comment]
If you need to compile your own version for some reason, the NumberInsight implementation is in the master branch.

BTW, tests/examples that exercise the functionality are in https://github.com/Nexmo/nexmo-dotnet/blob/3485e73ce51f559b0bdfa4842c69740f4e9bb367/Nexmo.Api.Test.Integration/NumberInsightTest.cs

**Comment by gaupoit** [comment]
Thanks @smithrobs
