### ISSUE TITLE
ability to search by type (toll free, mobile or fixed)

### ISSUE THREAD

**Issue by SafeCab** [Nexmo/nexmo-dotnet#124]
hi,

Please can you add the ability to search by type of phone e.g. tollfree, fixed or mobile

I see it on your UI but its not possible in your api - I can search by feature but I need to search by type as well

thanks

Steve

**Comment by RabebOthmani** [comment]
Hello @SafeCab ,
Apologies for not getting back to you any sooner. 
Thank you for spotting this. This is indeed missing from our implementation and we will work on adding it as soon as possible.

**Comment by RabebOthmani** [comment]
issue solved as per the following PR https://github.com/Nexmo/nexmo-dotnet/pull/148
