### ISSUE TITLE
ability to restrict number searches to those numbers with no address requirements

### ISSUE THREAD

**Issue by SafeCab** [Nexmo/nexmo-dotnet#125]
certain countries have address requirements.  Please can you add the ability to restrict the search based on if the number has any address requirement.

I would like to offer this to my customers but at the moment I have to rule out by country - as this may change over time it would be great if I could add a restriction on the search to stop it happening if legislation changes

thanks

Steve

**Comment by RabebOthmani** [comment]
Hello @SafeCab ,
Apologies for not getting back to you any sooner. 
This isn't specifically an issue with the client library. Please contact our support team at support@nexmo.com, and they'll be able to help you.
