### ISSUE TITLE
Few days ago i successfully create an outbound call(.net mvc framework4.6.1 on win10), then i copy 100% same code to my working environment at home(.net core 2.x on mac os), then i started to get the exception "System.ArgumentException: 'RsaUsingSha alg expects key to be of RSA type" again ! Do i need change any.....like..configuration? or something else??

### ISSUE THREAD

**Issue by lidondon** [Nexmo/nexmo-dotnet#132]
Thank you for making this library better by submitting an issue. To ensure we can troubleshoot effectively,
please fill out this form in its entirety.

If you are submitting a feature request you may ignore this template and enter a free-form description of your request.
You may also contact the maintainers directly via the Nexmo Slack to discuss the feature.

### General description of the issue or question
(Please be as descriptive as possible. If this is a general Nexmo question (billing, usage, etc.) you
will receive a better experience by either [filing a support request](https://help.nexmo.com/hc/en-us/requests/new)
directly to Nexmo or asking in the [Nexmo Slack](https://developer.nexmo.com/community/slack).)

### Which target framework(s) of .NET can you reproduce this issue against?
(Examples: .NET Core 2.0, netcoreapp1.0, .NET Framework 4.6.2, etc.)

### Version or commit hash
Which version(s) of `CSharp.Nexmo.Client` did you encounter this issue?
 
### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please provide a code snippet or steps to reproduce the issue.

**Comment by judy2k** [comment]
Hi @lidondon. It looks like there's a problem with your credentials on your home machine - either they're missing or they're incorrect - it doesn't look like this is a code issue - it's an issue with your home working environment.
