### ISSUE TITLE
Voice API Call.Edit command does not work

### ISSUE THREAD

**Issue by ciaran1234** [Nexmo/nexmo-dotnet#139]
### General description of the issue or question
Cannot make an edit for a call as the CallEditCommand class has an invalid data type for the destination field. Currently it uses string, making it impossible to send a valid request.  It needs to be a complex type as it should consist of a type field and a string array for the url fields. I propose you use the following data type for the destination field within the CallEditCommand class:

public class CallEditCommandDestination
{
   public string type { get; set; }

`  public string [] url { get; set; }
} 

### Which target framework(s) of .NET can you reproduce this issue against?
All .Net Frameworks

### What operating system(s) is exhibiting this issue?
Windows, Linux

### Version or commit hash
Latest
 
### Expected Behavior
I should receive a HTTP 204 response. No errors should be thrown.

### Actual Behavior
Rest Api returns a HTTP 400 bad request:

{"type":400,"title":"Bad Request","invalid_parameters":[{"reason":"Cannot construct instance of `com.nexmo.vapi.resource.call.common.TransferDestination` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{ \"type\": \"ncco\", \"url\": [\"https://developer.nexmo.com/ncco/tts.json\"] }')","name":"destination"}]}

SDK throws an argument null exception when trying to parse above JSON.

### Steps to Reproduce
  var result = client.Call.Do(new Call.CallCommand
            {
                to = new[]
                  {
                    new Call.Endpoint
                    {
                        type = "phone",
                        number = "XXXXXX"
                    }
                },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = "XXXXXX"
                },
                answer_url = new[] { "https://nexmo-community.github.io/ncco-examples/first_call_talk.json" }
            });

    var response = client.Call.Edit(result.uuid, new CallEditCommand
            {
                action = "transfer",
                destination =  "{ \"type\": \"ncco\", \"url\": [\"https://developer.nexmo.com/ncco/tts.json\"] }"
            });

**Comment by RabebOthmani** [comment]
Hi @ciaran1234 ,
Thank you for pointing this out. I can see the problem. 
A release with a fix should be out soon :)

**Comment by RabebOthmani** [comment]
Hello @ciaran1234 ,
The latest version of the client Lib v3.2.4 should fix the problem. Please let me know if you encounter any other problems.
