### ISSUE TITLE
Read Settings (ApiKey,ApiSecret,..) from web.config

### ISSUE THREAD

**Issue by goneneren** [Nexmo/nexmo-dotnet#14]
It should be possible to load settings from web.config or manually set the configuration

**Comment by smithrobs** [comment]
Right. This was a breaking change in v2.0 - you will need to port your `web.config` `<appSettings>` to a JSON-formatted `settings.json` file ([example](https://github.com/Nexmo/nexmo-dotnet/blob/6b2dd44f9a19ba8f96fafec2b03874aec3cfa873/Nexmo.Samples.Voice.FirstTTS/settings.json.example)).

I do understand the need to keep existing configurations intact, particularly when using .NET 4.x and not Core/Standard. I debated adding a fallback that parsed `web.config` and decided to gauge the need for it first. I'll consider your post a 👍  for this functionality.

**Comment by smithrobs** [comment]
@goneneren v2.1.0 is out on NuGet and supports web.config. Please let me know if you run into any issues.
