### ISSUE TITLE
Support HMAC512 (and other HMAC variants) of signatures

### ISSUE THREAD

**Issue by janpieterz** [Nexmo/nexmo-dotnet#140]
I'm trying to implement it here given the docs but somehow the signature is always slightly off. I'm using an API key with HMACSHA512 signature. It'd be great to get support in the client as the docs recommend us using that.

My, rough, attempt looks like this, and fails. 

``` c#
var requestAsDictionary = JsonConvert.DeserializeObject<Dictionary<string, string>>(requestBody);
var signature = requestAsDictionary["sig"];
requestAsDictionary.Remove("sig");

var content = string.Join("", requestAsDictionary.OrderBy(x => x.Key)
	.Select(x => $"&{x.Key}={x.Value.Replace("&", "_").Replace("=", "_")}"));

var keyBytes = Encoding.UTF8.GetBytes(Environment.GetEnvironmentVariable("NexmoSignatureSecret"));
using (HMACSHA512 hmac = new HMACSHA512(keyBytes))
{
	bool error = false;

	byte[] calculatedSignature = hmac.ComputeHash(Encoding.UTF8.GetBytes(content));
	byte[] receivedSignature = Encoding.UTF8.GetBytes(signature);

	var generatedSig = ByteArrayToHexHelper.ByteArrayToHex(calculatedSignature).ToLower();

        var error =  SlowEquals(Encoding.UTF8.GetBytes(generatedSig),
        Encoding.UTF8.GetBytes(signature));

	if (error)
	{
		return new OkResult();
	}
}

**Comment by RabebOthmani** [comment]
Hi @janpieterz 
We've spotted the issue and a new release with a fix should be out this week.

**Comment by judy2k** [comment]
Hi @janpieterz,

I think you're missing a step - which is to hex-encode the calculated signature before comparing it to the received signature. 

I'd also recommend doing a case-insensitive comparison by converting both strings to lower or upper case before comparing equality.

Hope this helps!

**Comment by janpieterz** [comment]
@judy2k Yup, and yeah, we've changed to different methods based on the support request, trying to get MD5-HASH to work first of all. When testing we use the correct method for the correct setting.

**Comment by judy2k** [comment]
Hi Jan,

There's some stuff in that latest code block that's incorrect. The algorithm you're implementing is documented [here](https://developer.nexmo.com/concepts/guides/signing-messages#step-1-for-both-hash-and-hmac-signatures), and I've summarised it below, with some extra notes on things I think are important, and things that conflict with the code above:

• Sort params by key and remove the `sig` param
• For every *value* in the parameter list, replace all instances of & and = with an underscore _ (**You're doing URL encoding here instead**)
• Generate a string consisting of `&akey=value&bkey=value`. Note that there is an ampersand & at the start of the string, and no ampersand at the end!
•  Add signature secret to the end of the string, directly after the last value. **Without an &** - I think your algorithm results in an ampersand between the key-value pairs and the secret. It should look a bit like this: `&akey=value&bkey=valueyour_signature_secret`
• Pipe the result into MD5 and then binhex the resulting bytes to form a String.

**Comment by janpieterz** [comment]
Hi @judy2k .
Thanks for taking a look! 
I've taken the MD5 code from this repository and copied it (for MD5) so not sure how there'd be any differences. There's no extra `&` (verified by running and comparing), it's exactly like `&akey=value&bkey=valueyour_signature_secret`. 

The URL encoding was copied from here:
https://github.com/Nexmo/nexmo-dotnet/blob/452ffc92bc7c8a0bf43e08ca7dbbd496d271413e/Nexmo.Api/Request/SignatureHelper.cs#L27
My original (own) attempt doesn't do any URL encoding, only replaces those two characters.
The comparison is already lower case (signature provided is already lower, but forcing lower doesn't change it).

**Comment by janpieterz** [comment]
Peter on support figured it out with a sample, it had to do with the default ordering of .NET of strings.
Somehow `message-timestamp` gets ordered after `messageId`, while it's put the other way around.

I do wonder how the SignatureHelper here then works as this uses the same order mechanism.

**Comment by RabebOthmani** [comment]
@janpieterz Thanks for pointing out to the SignatureHelper Class. It looks it's out of date and needs updating.
Apologies for that. 
@judy2k and I are working on fixing that.

**Comment by janpieterz** [comment]
@RabebOthmani no worries, threw me around a little, who knew ordering a `-` was culture dependent 🤔 
Happy to pick up some work as I got a working HMACSHA512 (and presumably others as logic is mostly similar). Let me know you'd like me to pick up a part, my suggestions/current work is in #142 .

For your reference, final HMACSHA512 code on our end:

```c#
private static bool ValidateSignature(string requestBody, string signatureSecret)
{
	var requestAsDictionary = JsonConvert.DeserializeObject<Dictionary<string, string>>(requestBody);

	var signature = requestAsDictionary["sig"];
	requestAsDictionary.Remove("sig");

	var cleanedDictionary =
		requestAsDictionary.ToDictionary(x => x.Key, x => x.Value.Replace("&", "_").Replace("=", "_"))
			.OrderBy(x => x.Key, StringComparer.OrdinalIgnoreCase);

	var contentToSign = string.Join("", cleanedDictionary.Select(x => $"&{x.Key}={x.Value}"));
	var keyBytes = Encoding.UTF8.GetBytes(signatureSecret);
	using (HMACSHA512 hmac = new HMACSHA512(keyBytes))
	{
		byte[] calculatedSignature = hmac.ComputeHash(Encoding.UTF8.GetBytes(contentToSign));
		var generatedSig = ByteArrayToHexHelper.ByteArrayToHex(calculatedSignature).ToUpperInvariant();

		var validSignature = SlowEquals(Encoding.UTF8.GetBytes(generatedSig),
			Encoding.UTF8.GetBytes(signature.ToUpperInvariant()));

		return validSignature;
	}
}
```

**Comment by slorello89** [comment]
@janpieterz I have added signature / validation support for HMACS in v4.1.2 of the SDK - you are indeed right - the _/- ordering threw me threw a loop :). 

Snippets for how to go about signing / validation with the SDK can be found here: https://developer.nexmo.com/concepts/guides/signing-messages/dotnet
