### ISSUE TITLE
Connect callers to a conference

### ISSUE THREAD

**Issue by tyronent** [Nexmo/nexmo-dotnet#143]
How can one connect callers to a conference using the .net library?

I'm trying to follow the below link but there is no .net example:
https://developer.nexmo.com/voice/voice-api/building-blocks/connect-callers-into-a-conference

**Comment by RabebOthmani** [comment]
Hi @tyronent ,
I will add the missing building block to the quickstarts. 
Could I please ask you to open an issue on https://github.com/nexmo-community/nexmo-dotnet-quickstart 
I'm going to close this one since there's no work to be done on the Client Library. Thank you.
