### ISSUE TITLE
user agent header formatting error

### ISSUE THREAD

**Issue by speechwrecko** [Nexmo/nexmo-dotnet#145]
### General description of the issue or question
We started see the following our logs

System.FormatException: The format of value 'dotnet/Linux4.9.0-7-amd64#1SMPDebian4.9.110-3+deb9u2(2018-08-13).NETCore4.6.27129.04' is invalid

Upon further investigation we discvoered this user agent header was set in the library and the string was too long or improperly formatted .. causing an error

### Which target framework(s) of .NET can you reproduce this issue against?
(Examples: .NET Core 2.0, netcoreapp1.0, .NET Framework 4.6.2, etc.)
4.6.2

### What operating system(s) is exhibiting this issue?
Debian / Linux

### Version or commit hash
Which version(s) of `CSharp.Nexmo.Client` did you encounter this issue?
2.2.0
 
### Expected Behavior
What should have happened?
No error

### Actual Behavior
What actually happened?
Error

### Steps to Reproduce
Please provide a code snippet or steps to reproduce the issue.
See above

**Comment by judy2k** [comment]
Hi @speechwrecko - thanks for the bug report! I'm currently in the process of porting to .NET Core, and I've also found this issue - we should make a new release later this week to fix it.

**Comment by lval** [comment]
Any update on this? I'm encountering this error on Debian with framework .NET Core 2.2 using Nexmo.Csharp.Client 4.0.

**Comment by slorello89** [comment]
@lval and @speechwrecko - fyi just submitted #191 which ought to fix this issue - the .NET HTTP library is objecting to the parentheses surrounding the date - I'm moving the User Agent's descriptor to be in line with our specs which will resolve the issue - this should hopefully be coming soon to 4.3.1

**Comment by slorello89** [comment]
Hi @lval and @speechwrecko - I just released version 4.3.1 - which should fix the issue - I did not realize I closed this issue earlier - was meant to be kept open until today - if you encounter this issue again please let me know!
