### ISSUE TITLE
Sending text message in Nexmo.Api version 2.1 broken

### ISSUE THREAD

**Issue by Sythion** [Nexmo/nexmo-dotnet#15]
Using the github examples, whenever a text is sent using SMS.Send, an error code of 2 is returned with the error text "Missing username."  Had to downgrade to version 2.0 to resolve this issue.

**Comment by smithrobs** [comment]
Hmm. A few things to try:
- v2.1 changed the `settings.json` structure slightly. Are your Nexmo configuration options inside of an `appSettings` object?
- Which OS and Framework are you using?
- Would you be able to provide a sanitized version of the `SMS.SMSRequest` object that you pass to `SMS.send`?

**Comment by lservant** [comment]
Same Error:

> Dim request As Api.SMS.SMSRequest = New Api.SMS.SMSRequest With{
>         .from = fromPhone,
>         .to = guestPhone,
>         .body = msgBody
>       }

> 'send message to Nexmo
>       Dim message = Api.SMS.Send(request)

Where from and to are strings containing standardized phone numbers, and body is a simple test string: "Hey, this is a test!".  I'm building this with .Net 4.5.2 on Windows 10 using VS2013.  Here's my config:

>     <add key="Nexmo.UserAgent" value="greenvelopesms/1.0" />
>     <add key="Nexmo.Url.Rest" value="https://rest.nexmo.com" />
>     <add key="Nexmo.Url.Api" value="https://api.nexmo.com" />
>     <add key="Nexmo.api_key" value="mykey" />
>     <add key="Nexmo.api_secret" value="mysecret" />

where mykey and mysecret are actually my key and secret, sanitized for this post.

**Comment by smithrobs** [comment]
Thank you! When you mention `web.config` - where is it located in relation to the executing process? Is this a web application or console application?

I am aware of an issue relating to console applications: The XML-style config file must be named `app.config` or `web.config` and must be in the same directory as the executable. The file cannot be named `<executable filename>.exe.config` as it is traditionally named. I will fix this in a release soon or make a note of it in the readme.

**Comment by smithrobs** [comment]
I just pushed out a v2.1.1 release that looks for the 'legacy' convention of `executing_process_filename.exe.config` file for XML configuration. Let me know if this helps this issue or not.

**Comment by lservant** [comment]
I'm building a web application, and the code is actually being held in a dll that we're deploying to a web site.  I was able to get it to work by dropping a settings.json at the root of the web site in addition to the web.config holding all my other settings.

Looking at your responses, though it seems that fix should take care of it.  I'll give it a shot and see!

Thank you for your quick feedback!

**Comment by smithrobs** [comment]
Not a problem. Your real-world usage is valuable feedback, particularly since the configuration part of the library is in flux. I'm trying to support as many different scenarios as possible but want to be focused on the ones people are putting to use.

**Comment by lservant** [comment]
I had to write up a quick blank web application project to compare Twilio vs Nexmo (message queuing in particular).  I included 2.1.2 to test this as well. I still seem to be getting that missing username error using similar code to my previous post, but directly in the code behind when trying to read from web.config alone.

Again, fixed it by putting the settings.json in there in addition to web.config.

**Comment by smithrobs** [comment]
I'm afraid you might be getting [this related issue](https://github.com/Nexmo/nexmo-dotnet/issues/17#issuecomment-265600338) now. The lib is not calling SetBasePath on the configuration builder because IHostingEnvironment isn't available in all use cases (console applications, for example). This means the JSON configs have to be insidethe web app bin for the time being.

**Comment by smithrobs** [comment]
Closing this for now as it seems #17 will address this.
