### ISSUE TITLE
Installing the library to a .NET also installs .NET Core libraries

### ISSUE THREAD

**Issue by kenken023** [Nexmo/nexmo-dotnet#150]
### General description of the issue or question
Installing the library to a ASP.NET MVC project also installs .NET Core libraries such as ASP.NET Core MVC, etc which is not needed. 

### Which target framework(s) of .NET can you reproduce this issue against?
.NET Framework 4.6.1

### What operating system(s) is exhibiting this issue?
Windows

### Version or commit hash
Nexmo.Csharp.Client 3.2.4
 
### Expected Behavior
Should not install .NET Core libraries

### Actual Behavior
Installed the unnecessary .NET Core libraries

Please see attached screenshot of dependencies in a .NET project:

![image](https://user-images.githubusercontent.com/3609248/53943246-a9b7b700-40f7-11e9-8495-bb8a551dfe3d.png)

**Comment by kenken023** [comment]
Workaround is to use the REST API.

**Comment by kenken023** [comment]
Any updates? :)

**Comment by slorello89** [comment]
Hi @kenken023 

I have removed the ASP.NET Core dependency from the non core versions.

**Comment by slorello89** [comment]
I'm closing out this issue now - as it should be fixed - if you continue to see it please feel free to reopen.

thanks!
