### ISSUE TITLE
Whatsapp message type

### ISSUE THREAD

**Issue by Caloyski** [Nexmo/nexmo-dotnet#152]
Good day,

are you going to support WhatsApp messages?

I tried the following code

```
            var client = new Client(creds: new Nexmo.Api.Request.Credentials {
                ApiKey = "**myapikey**",
                ApiSecret = "*mysecret*"
            });

            var results = client.SMS.Send(request: new SMS.SMSRequest {
                from = "Acme",
                to = "391234567",
                text = "A test SMS sent using the Nexmo SMS API",
                type = "whatsapp"
            });
```

and the results variable contained the following message: "Invalid Message Type"

**Comment by RabebOthmani** [comment]
Hello @Caloyski 
We do support WhatsApp with the [Messages API ](https://developer.nexmo.com/messages/overview). 
It's still Beta therefore not implemented in the Client Lib but eventually, it will be.
