### ISSUE TITLE
JWT creation does not work in 4.6+ on OSX

### ISSUE THREAD

**Issue by fauna5** [Nexmo/nexmo-dotnet#154]
### General description of the issue or question
The library errors when using JWTs in 4.6+ on OSX. 

This line uses Cryptography Next Generation (CNG) implementation of the RSA algorithm which is only available in windows
https://github.com/Nexmo/nexmo-dotnet/blob/3c0bddbc8f1526f7469774ff596ddf35050e2011/Nexmo.Api/PemParse.cs#L259
See https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.rsacng?view=netframework-4.8

`var RSA = new RSACryptoServiceProvider();` 

is available on my platform, so using this instead is an option.

### Which target framework(s) of .NET can you reproduce this issue against?
.NETCoreApp,Version=v2.1.

### What operating system(s) is exhibiting this issue?
OSX 10.14.4

### Version or commit hash
v3.3.1
 
### Expected Behavior
I try to make a call using a private key

### Actual Behavior
It threw an error 

### Steps to Reproduce
```
        static private JArray CreateNCCO()
        {
            dynamic TalkNCCO = new JObject();
            TalkNCCO.action = "talk";
            TalkNCCO.voiceName = "Salli";
            TalkNCCO.text = "What do you get if you cross a telephone with an iron? A smooth operator!";
            JArray ncco = new JArray();
            ncco.Add(TalkNCCO);
            return ncco;
        }

        public static void Main(string[] args)
        {            
           var client = new Client(creds: new Nexmo.Api.Request.Credentials
            {
                ApiKey = <key>
                ApiSecret = <key_secret>
                ApplicationId = <app id>
                ApplicationKey = <key>
            });

            var results = client.Call.Do(new Call.CallCommand
            {
                to = new[]
              {
                new Call.Endpoint {
                  type = "phone",
                  number = "<my number>"
                }
              },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = "<my number>"
                },
                Ncco = CreateNCCO()
            });
        }
```

**Comment by slorello89** [comment]
@fauna5  thanks so much for the PR - this will be in the SDK 4.2.1 release!

**Comment by slorello89** [comment]
@fauna5 this is in v4.2.1 which I just pushed out yesterday - thanks so much again for your contribution!.
