### ISSUE TITLE
Send Nexmo SMS from Azure Function

### ISSUE THREAD

**Issue by faeezkehzen** [Nexmo/nexmo-dotnet#158]
Thank you for making this library better by submitting an issue. To ensure we can troubleshoot effectively,
please fill out this form in its entirety.

If you are submitting a feature request you may ignore this template and enter a free-form description of your request.
You may also contact the maintainers directly via the Nexmo Slack to discuss the feature.

### General description of the issue or question
(Please be as descriptive as possible. If this is a general Nexmo question (billing, usage, etc.) you
will receive a better experience by either [filing a support request](https://help.nexmo.com/hc/en-us/requests/new)
directly to Nexmo or asking in the [Nexmo Slack](https://developer.nexmo.com/community/slack).)

### Which target framework(s) of .NET can you reproduce this issue against?
(Examples: .NET Core 2.0, netcoreapp1.0, .NET Framework 4.6.2, etc.)
.NET Framework 4.61(Azure Function)
### What operating system(s) is exhibiting this issue?
Windows 10
### Version or commit hash
Which version(s) of `CSharp.Nexmo.Client` did you encounter this issue?
 3.3.1
### Expected Behavior
What should have happened?
Send SMS by schedule using azure function.
### Actual Behavior
What actually happened?
it doesnt send the email. This is the error "The type initializer for 'Nexmo.Api.Configuration' threw an exception"
### Steps to Reproduce
Please provide a code snippet or steps to reproduce the issue.

**Comment by slorello89** [comment]
Hi Fazeekehzen,

I'm closing this issue as I haven't heard back from you - feel free to reopen with the full stack trace.

thanks,
