### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.'

### ISSUE THREAD

**Issue by pickapool** [Nexmo/nexmo-dotnet#164]
Thank you for making this library better by submitting an issue. To ensure we can troubleshoot effectively,
please fill out this form in its entirety.

If you are submitting a feature request you may ignore this template and enter a free-form description of your request.
You may also contact the maintainers directly via the Nexmo Slack to discuss the feature.

### General description of the issue or question
(Please be as descriptive as possible. If this is a general Nexmo question (billing, usage, etc.) you
will receive a better experience by either [filing a support request](https://help.nexmo.com/hc/en-us/requests/new)
directly to Nexmo or asking in the [Nexmo Slack](https://developer.nexmo.com/community/slack).)

### Which target framework(s) of .NET can you reproduce this issue against?
(Examples: .NET Core 2.0, netcoreapp1.0, .NET Framework 4.6.2, etc.)

### Version or commit hash
Which version(s) of `CSharp.Nexmo.Client` did you encounter this issue?
 
### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please provide a code snippet or steps to reproduce the issue.

**Comment by slorello89** [comment]
Hi @pickapool - it looks like for some reason your runtime is trying to read the Microsoft.Extensions.Configuration.Abstractions as 1.1.2 where it is actually the 1.0.2 version, and barfing. Can you try installing Microsoft.Extensions.Configuration.Abstractions v 1.1.2 in the package manager and running it again.

**Comment by pickapool** [comment]
I lower down the version of nexmo 4.1.0 to 4.0.0 and it works

**Comment by slorello89** [comment]
Hi @pickapool 

this issue should be fixed in 4.1.1

**Comment by slorello89** [comment]
As this issue should be resolved in 4.1.1 I am closing it - if you still have this problem feel free to reopen.
