### ISSUE TITLE
Please add API for downloading recordings

### ISSUE THREAD

**Issue by hiral2609** [Nexmo/nexmo-dotnet#165]
Please add API for downloading recordings. This is already part of other framework's apis so should be relatively very easy to add it for .NET

**Comment by slorello89** [comment]
Hi @hiral2609 - Recording downloading was added to the API with the release of v4.1 

invoke like so:

```
var client = new Client(creds: new Nexmo.Api.Request.Credentials
            {
                ApiKey = "NEXMO_API_KEY",
                ApiSecret = "NEXMO_API_SECRET",
                ApplicationId = "NEXMO_APPLICATION_ID",
                ApplicationKey = "NEXMO_APPLICATION_PRIVATE_KEY"
            });
var response = client.Call.GetRecording(recordingUrl);
```

**Comment by hiral2609** [comment]
This is great! Thank you for this! Is there a place where I can subscribe to releases notifications and see the changes in each revision.

**Comment by hiral2609** [comment]
Found my answer - https://github.com/Nexmo/nexmo-dotnet/releases

**Comment by lornajane** [comment]
You answered your own question :) You can also follow changes for all our APIs and SDKs on our changelog page https://changelog.nexmo.com/
