### ISSUE TITLE
How to create strong typed ncco object for websocket?

### ISSUE THREAD

**Issue by tellstoriesatbedtym** [Nexmo/nexmo-dotnet#170]
Looks like the version SDK 4.2 is missing option to create strong typed ncco object for websocket action. Looking at the API, it seems to only support these:

![image](https://user-images.githubusercontent.com/39365214/67910823-75d74900-fb41-11e9-99c9-8227d48a41d8.png)

**Comment by slorello89** [comment]
Hi @tellstoriesatbedtym ,

websocket is not a valid action - you would use a connect Action with a websocket endpoint.

thanks!

**Comment by tellstoriesatbedtym** [comment]
I see, let me try it.

**Comment by slorello89** [comment]
@tellstoriesatbedtym 

I'm assuming this is functional as it's been functional in my testing and we haven't heard an update in a while - thanks so much for raising the issue - always good to have another sanity check - if you encounter any more issues feel free to open an issue or ping me in the community slack channel.
