### ISSUE TITLE
Use correct basic data types instead of string for strong-typed NCCO objects

### ISSUE THREAD

**Issue by tellstoriesatbedtym** [Nexmo/nexmo-dotnet#171]
I was looking at creating the ncco object for record action, and it seems there are some properties which are taking string instead of base types like bool or int.

For eg, look at the TimeOut and BeepStart property values:
![image](https://user-images.githubusercontent.com/39365214/67910900-bd5dd500-fb41-11e9-889e-f59e671ce49a.png)

**Comment by slorello89** [comment]
Hi @tellstoriesatbedtym,

A little strange I know but those types are correct for both timeout and beepStart.

**Comment by slorello89** [comment]
closing this issue as I've not seen an update for some time and it appears functional in my testing as is.
