### ISSUE TITLE
ip_address is ignored when passed into Verify Request.

### ISSUE THREAD

**Issue by slorello89** [Nexmo/nexmo-dotnet#179]
https://github.com/Nexmo/nexmo-dotnet/blob/d7968de5c1805d55d2fc9c1069ac8f880296ca5b/Nexmo.Api/NumberVerify.cs#L141-L151

If an app passes in an ip_address to a Verify Check request - it is not added to the parameters of the request.

**Comment by lornajane** [comment]
It is also not used by the API for anything so this probably isn't very high priority. It was used by an earlier integration but I was asked to update the spec to mark the field deprecated.

**Comment by slorello89** [comment]
As the API isn't actually used and the field is being deprecated I'm going to go ahead and close this issue.
