### ISSUE TITLE
Request aborted: SSL/TLS security channel could not be created.

### ISSUE THREAD

**Issue by ihoeysun** [Nexmo/nexmo-dotnet#181]
Use Nexmo sms SDK in .NET Framework 4.5.2,

Throw some exceptions：
Request aborted: SSL/TLS security channel could not be created.

StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nexmo.Api.Request.ApiRequest.DoRequest(String method, Uri uri, Dictionary`2 parameters, Credentials creds)
   at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds)
   at Nexmo.Api.ClientMethods.SMS.Send(SMSRequest request, Credentials creds)

How to solve？thx

**Comment by slorello89** [comment]
Hi @ihoeysun  - pre 4.6 .NET versions do not set TLS to 1.2 by default (which is what is required to speak to the Nexmo APIs. We do not explicitly set the TLS version in our software version at the moment. There are a few ways that you can do it.

1. In your code you can explicitly set the TLS version to 1.2 with the following line:  `System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;` this is probably the simplest from your perspective - but it is globally hard coding a TLS version.

2. You can update to .NET framework version 4.6 or later - which supports TLS 1.2 by default.

3. You can set registry keys of your machine to instruct your software to use the default TLS version of your system see Microsoft's writeup about it [here](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#for-net-framework-35---452-and-not-wcf)

**Comment by ihoeysun** [comment]
I am very glad to receive your reply. Thank you very much

**Comment by slorello89** [comment]
#182

**Comment by slorello89** [comment]
Hi @ihoeysun - I'm glad this helped you - I left a note in our README that should help guide anyone stuck in this predicament down the line. I'm going to close out this issue as it appears your issue has been resolved.
