### ISSUE TITLE
WhatsApp non-beta timeline

### ISSUE THREAD

**Issue by janpieterz** [Nexmo/nexmo-dotnet#192]
The WhatsApp messaging API wasn't implemented (yet) as it was in beta. Any timeline idea on releasing this as non-beta? 

As a feature suggestion, it'd be interesting to, for future releases, have an easy way to speak to the Nexmo API via this library (handling authentication and other underlying tasks), exposing something like a custom request sender.

**Comment by slorello89** [comment]
Hi @janpieterz thanks for writing in - we don't have a date yet when the messages stuff will be out of beta. 

As per your request to open up the SDK to allow custom requests - thanks for the feedback it's definitely something we are considering.

FYI for messages and dispatch - I created a couple samples in our blog about using it with .NET that should make your integration a snap. 

Check out: https://www.nexmo.com/blog/2019/12/19/santas-nexmo-helper-c-advent-series-dr

Only update is that in the newer version of the SDK's you can generate the simple JWT you'll need for messages yourself so you don't even need to do the token generation stuff

https://www.nexmo.com/blog/2020/01/15/announcing-nexmos-net-server-sdk-version-4-3-0-release-dr

**Comment by janpieterz** [comment]
@slorello89 great, the JWT calculation is a nice help. We'll migrate our code over to use it.

**Comment by hognevevle** [comment]
Any updates here on the timeline? I'd love to see support for Messages API in this SDK.
