### ISSUE TITLE
StreamAction request serialization issue

### ISSUE THREAD

**Issue by taylus** [Nexmo/nexmo-dotnet#196]
### General description of the issue or question
Hello, I'm running into an HTTP 400 Bad Request error while using `StreamAction` to play audio in a phone call:

```plain
Message: 
  Test method Nexmo.Api.Test.Integration.CallTest.should_call_with_stream_NCCO threw exception: 
  System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
Stack Trace: 
  HttpResponseMessage.EnsureSuccessStatusCode()
  VersionedApiRequest.DoRequest(String method, Uri uri, Object payload, Credentials creds) line 188
  Call.Do(CallCommand cmd, Credentials creds) line 289
  CallTest.should_call_with_stream_NCCO() line 75
```

I observed the REST API traffic and noticed that the `streamUrl` property is being serialized as a single string. It looks like per [this documentation](https://developer.nexmo.com/voice/voice-api/ncco-reference#stream) this should serialize as an array.

I'm able to circumvent this issue by setting the `Ncco` `JArray` property on my `CallCommand`, but this is marked as deprecated in favor of the strongly-typed `NccoObject` of type `Ncco` (and I'd rather use that, instead!)

### Which target framework(s) of .NET can you reproduce this issue against?
I'm pretty sure it's affecting all of them, but I've only tried .NET Core 2.1 so far.

### What operating system(s) is exhibiting this issue?
Windows 10

### Version or commit hash
Which version(s) of `CSharp.Nexmo.Client` did you encounter this issue?
4.3.1
 
### Expected Behavior
What should have happened?
Call should go through and play the mp3 at the specified URL.

### Actual Behavior
What actually happened?
Library throws either a `HttpRequestException` or `ArgumentNullException` upon receiving or deserializing the response, respectively, based on the "Nexmo.Api.EnsureSuccessStatusCode" config setting.

### Steps to Reproduce
I will link a PR shortly with tests reproducing the issue + a minimal suggested fix.

**Comment by slorello89** [comment]
will close this with the next release.

**Comment by slorello89** [comment]
Closing this out per the new 4.3.2 release
