### ISSUE TITLE
Support for US Short Code 

### ISSUE THREAD

**Issue by Godminders** [Nexmo/nexmo-dotnet#20]
I don't see any examples for sending a message with the US Short Codes API.  Does this library support Event based alerts?

**Comment by smithrobs** [comment]
There is support for short codes. You can find a couple tests that demonstrate the ability [in ShortCodeTest.cs](https://github.com/Nexmo/nexmo-dotnet/blob/050792eb8d7984560287904c2436bcbaccc7865b/Nexmo.Api.Test.Integration/ShortCodeTest.cs).

Feel free to comment here or in the Nexmo slack if you have additional questions regarding the short code implementation.

**Comment by Godminders** [comment]
Here is how I'm calling it.


  Dictionary<string, string> nexmoParams = new Dictionary<string, string>();
>             nexmoParams.Add("godminders-sms", "TestMessage");
>             var response = ShortCode.RequestAlert(new
> ShortCode.AlertRequest
>             {
>                 to = "17035551212",
>                 clientRef="1",
>             }, nexmoParams);
>


I'm getting the errror "missing username".   I have the api-key and
api-secret set in web.config.

- Kevin

**Comment by smithrobs** [comment]
I know we talked on the Nexmo Slack a bit, but I just pushed a pre-release version v2.2.0-rc1 to NuGet. This release includes logging support to debug configuration issues. If you continue to have trouble with authentication (such as "missing username"), please give this version a try. Your feedback would be much appreciated! 😄

**Comment by Godminders** [comment]
Awesome.  Thx.
