### ISSUE TITLE
'The type initializer for 'Nexmo.Api.Configuration' threw an exception.'

### ISSUE THREAD

**Issue by ahron33** [Nexmo/nexmo-dotnet#201]
I am getting this error whe i am trying to send a call voice throw an android app in visual studio
.NET 2.0
do i need add more details?

**Comment by slorello89** [comment]
Hi @ahron33 - I'm afraid the .NET Framework 2.0 is not supported by the Nexmo .NET SDK - see list of supported versions here: https://github.com/nexmo/nexmo-dotnet#targeted-frameworks - 

If you are in fact using .NET core 2.0 - which is supported I'll have to ask you to make sure that you are using the latest version of the .NET SDK - and to ask you to check to see if your application is using another version of Microsoft.Extensions.Configuration - and to let me know which version.

thanks,

**Comment by ahron33** [comment]
> Hi @ahron33 - I'm afraid the .NET Framework 2.0 is not supported by the Nexmo .NET SDK - see list of supported versions here: https://github.com/nexmo/nexmo-dotnet#targeted-frameworks -
> 
> If you are in fact using .NET core 2.0 - which is supported I'll have to ask you to make sure that you are using the latest version of the .NET SDK - and to ask you to check to see if your application is using another version of Microsoft.Extensions.Configuration - and to let me know which version.
> 
> thanks,

my max version on the android sln is 2.1 it wont support it? no way to do it?

**Comment by slorello89** [comment]
Hi @ahron33 - I just noticed that you were referring to running this in an android app. I'm afraid - that regardless of .NET version we do not support that. The .NET server SDK is meant to be running server-side only - as running client-side risks the leak of your application's secrets (private key, API secret). If you are looking to use the .NET server SDK - my recommendation to you is that whatever Android app you're building you add a backend component using asp.net and use this web-service do whatever you need to do with the server SDK.

FYI - there is an android SDK available https://developer.nexmo.com/client-sdk/overview - that enables you to do things like in-app messaging, and in-app voip calls - that may be something that more directly does what you're looking for. For this you'll also need a back-end component to generate your JWTs FYI - so it's not a completely client-side solution.

hope this helps!

**Comment by ahron33** [comment]
> Hi @ahron33 - I just noticed that you were referring to running this in an android app. I'm afraid - that regardless of .NET version we do not support that. The .NET server SDK is meant to be running server-side only - as running client-side risks the leak of your application's secrets (private key, API secret). If you are looking to use the .NET server SDK - my recommendation to you is that whatever Android app you're building you add a backend component using asp.net and use this web-service do whatever you need to do with the server SDK.
> 
> FYI - there is an android SDK available https://developer.nexmo.com/client-sdk/overview - that enables you to do things like in-app messaging, and in-app voip calls - that may be something that more directly does what you're looking for. For this you'll also need a back-end component to generate your JWTs FYI - so it's not a completely client-side solution.
> 
> hope this helps!

i am using this app only to my self so i dont think so that it will be leaked... (fix me if i am worng)
but you send a link what do i need to do with this?

**Comment by slorello89** [comment]
Hi @ahron33 - that link is to our docs on the Client SDK, which is available for Android, and which does supply in-app voice and messaging capabilities. The documents do a better job describing what the SDK does - and how you can build with it than I can. If you have any questions regarding it I'd encourage you to reach out to us on our community [slack] (https://developer.nexmo.com/community/slack).

If you are looking to use this SDK the application should be server-side. As we do not support .NET 2.0 or .NET on Android I'm going to close this issue.

thank you for writing in.
