### ISSUE TITLE
ArgumentNullException on Call.Do

### ISSUE THREAD

**Issue by theonlynexus** [Nexmo/nexmo-dotnet#21]
I trying to run the voice call example from the API solution with a little twist (I would like to do everything from my C# application, so I am spawning a Thread to later check on the call status), but I always run into a `ArgumentNullException` in `mscorlib.dll`. Any clues?

```c#
var thread = new System.Threading.Thread(() => {
var response = Nexmo.Api.Voice.Call.Do(new Nexmo.Api.Voice.Call.CallCommand
{
    to = new[] {
        new Nexmo.Api.Voice.Call.Endpoint {
            type = "phone",
            number = number
        }
    },
    from = new Nexmo.Api.Voice.Call.Endpoint {
        type = "phone",
        number = "01234567"
    },
    answer_url = new[] {
        "https://nexmo-community.github.io/ncco-examples/first_call_talk.json"
    }
});
});
thread.Start();
```

**Comment by theonlynexus** [comment]
I think I found the problem. The new Voice API requires an application to be created on Nexmo's backend and it requires the new JWT based authentication. 
I'll see if creating the app and adding authentication parameters to the appconfig.json file solves the problem.

**Comment by smithrobs** [comment]
Sorry for the holiday delay. Yes, you are correct that the Voice API calls require a valid Nexmo application ID and key - please see the Nexmo [application docs](https://docs.nexmo.com/tools/application-api?utm_source=DEV_REL&utm_medium=github&utm_campaign=csharp-client-library) for full info. You will need to create an application either through the `Nexmo.Api.Application` class or some other way of your choice in order to provide values for `Nexmo.Application.Id` and `Nexmo.Application.Key` inside `appconfig.json`. 

All that said, the lib should emit a clearer error message than `ArgumentNullException`. Ref'ing #7 and #8 so I keep this in mind.

Closing this question - feel free to comment here or in the Nexmo Slack group if you continue to have issues.

**Comment by theonlynexus** [comment]
Sorry to bother again, but I am struggling to make this work.
Things I have done:
- Created an application using a curl POST to `https://api.nexmo.com/v1/applications`
- Got the answer and saved it to a file for future reference
- Verified the creation using a curl GET to `https://api.nexmo.com/v1/applications`
- Copied the private key to a file named private.key and replaced each `"\n"` occurrence with an actual newline
- Added `Nexmo.Application.Id` and `Nexmo.Application.Key` to app.config (I still didn't get around to using a json file for config loading)

Now the `ArgumentNullException` is gone, but I get an `ArgumentException` from jose-jwt: 

> "RsaUsingSha alg expects key to be of AsymmetricAlgorithm type."

which is funny since I am using the key provided by Nexmo.

Clues? Thanks for taking time to answer even is this festive period.

**Comment by smithrobs** [comment]
No problem; I'm happy to get feedback on library usage and to get you up and running!

Yes, this is a bit tricky, especially if you are on Windows. Everything you did looks good. My guess is the `private.key` file is UTF-8 (the library expects ASCII) and may have a byte order mark. [Check out this StackOverflow article](http://stackoverflow.com/questions/1068650/using-awk-to-remove-the-byte-order-mark) for some linux-based hints to remove it. Text editors usually have this ability as well (e.g. Visual Studio and [Advanced Save](https://msdn.microsoft.com/en-us/library/dxfdkfke.aspx)).

I am finishing up v2.2 this week and this is one of the areas (Application support) I have plans to make easier. I'm hoping to get a release out before 2017. 😄

**Comment by theonlynexus** [comment]
Hello, once more. 
I tried everything I know to set the encoding to plain ASCII, but I couldn't solve the issue. 

Any other idea?

**Comment by smithrobs** [comment]
Woo 2017! 😄 

Hm. Can you try saving the private key after creating the application? Example:

```csharp
var appRequest = new ApplicationRequest
{
    name = "appgentest",
    type = "voice",
    answer_url = "https://abcdefg.ngrok.io/api/voice",
    event_url = "https://abcdefg.ngrok.io/api/voice",
};

var appResp = Application.Create(appRequest);
System.IO.File.WriteAllText(appResp.keys.private_key, $"{appResp.id}private.key");
```

Then try specifying the new app ID and keyfile via config. I do want the library to handle all this for you as it definitely can be tricky. Also note that the Application API is listed as "Early Adopter" for Nexmo and I've seen instances where the API itself returns incorrect HTTP statuses like 403.

**Comment by theonlynexus** [comment]
Sorry for not getting back to you, I have been quite busy with other tasks. I'll try your suggestion out during the day and the post the results.

**Comment by smithrobs** [comment]
Not a problem. I did want to let you know I pushed a pre-release version v2.2.0-rc1 to NuGet. I can't say this will directly address your issue, but it includes configuration and request logging which may be helpful for troubleshooting.

**Comment by theonlynexus** [comment]
So, I did the test and the result is the same ("RsaUsingSha alg expects key to be of AsymmetricAlgorithm type.")

the code I used is the following:
```C#
    var appRequest = new Nexmo.Api.ApplicationRequest
    {
         name = "appgentest",
         type = "voice",
         answer_url = "some_url",
         event_url = "some_url",
    };
    var appResp = Nexmo.Api.Application.Create(appRequest);
    System.IO.File.WriteAllText(appResp.id+"_private.key", appResp.keys.private_key, System.Text.Encoding.ASCII);
```

**Comment by smithrobs** [comment]
Sorry for the delay. I figured out what is going on:

You are seeing this error because the Nexmo API switched from providing PKCS#1 formatted keys during application creation to PKCS#8. This library currently expects PKCS#1.

You can get around this with `openssl` as it will automatically convert it for you:

```
openssl rsa -in <KEY FILENAME> -out <OUTPUT KEY FILENAME>
```

I will update the library accordingly soon! Thank you for your patience. 😄 

(ref #22)

**Comment by smithrobs** [comment]
@theonlynexus I just pushed 2.2.0-rc2 to NuGet, which fixes this issue. I expect to release 2.2.0 in the next few days, but if you need this ASAP please pull down the pre-release version from NuGet.

**Comment by theonlynexus** [comment]
Hi, thanks for the info and the patch. I'll wait until the official 2.2.0 release.

**Comment by pmaxim** [comment]
I have a voice call on my computer. When placed in production (Windows IIS).
The file private.key finds successfully, but gives an error "Value cannot be null.
Parameter name: value"
The file *.key created:

Nexmo.Api.Application.Create(appRequest, cr);
nexmo app:create
site
In all cases, the same error
Tell me what could be the problem?
Thanks
Maxim (Kiev, Ukraine)
