### ISSUE TITLE
How handle the issues that is thrown by nexmo API 

### ISSUE THREAD

**Issue by sejapsit** [Nexmo/nexmo-dotnet#216]
I m using verify request and verify check API which throws error i want to know how to handle it in .net

Verify request 
1.	If I add wrong number “Verify Request Failed with status: 3 and Error Text: Invalid value for param: number”
2.	If I verify concurrently “Verify Request Failed with status: 10 and Error Text: Concurrent verifications to the same number are not allowed”
VerifyCheck
1.	If I re-verify my code “Verify Request Failed with status: 6 and Error Text: The Nexmo platform was unable to process this message for the following reason: Request 'requestId' was not found or it has been verified already.”
2.	If I enter wrong code “Verify Request Failed with status: 16 and Error Text: The code provided does not match the expected value”

Below are the errors screen shots thrown in catch I want them in response

![e1](https://user-images.githubusercontent.com/26812592/90622036-34c83680-e232-11ea-9862-e4c7ab7bdd7e.png)
![e2](https://user-images.githubusercontent.com/26812592/90622050-38f45400-e232-11ea-93dd-9ff97be29869.png)
Also in catch nexmo sends response but in catch I can’t access, ex.Response as Exception poco do not contain “Response”

Also i m attaching my code 
[nexmoAPICode.txt](https://github.com/Nexmo/nexmo-dotnet/files/5095691/nexmoAPICode.txt)

**Comment by slorello89** [comment]
Hi @sejapsit - great question, 

A commented out region of your code is trying to catch a `VerifyResponseException` which is an exception thrown by the legacy NumberVerify class - that class, and the corresponding exception was deprecated in 5.0 (the class was preserved to make the upgrade path easier) Unfortunately, it occupies the `Nexmo.Api` namespace - so I can see why this would be confusing.

The exception you should be catching is the [NexmoVerifyResponseException](https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/Verify/NexmoVerifyResponseException.cs) which will contain exactly what you're looking for.

**Comment by sejapsit** [comment]
I tried using this " NexmoVerifyResponseException" but it get catch in "Exception" as you can see in Screen shots that's the reason i comment it

**Comment by slorello89** [comment]
Hi @sejapsit 

Taking another look I still don't see you catching the `NexmoVerifyResponseException`, again you're catching the `VerifyResponseException`, which is a legacy class, and a `NexmoHttpRequestException` (which is thrown when the client encounters a 400/500 error code when communicating with the API).

**Comment by sejapsit** [comment]
Hi @slorello89 
okay ya I got it thanks I ll try and let you know

**Comment by sejapsit** [comment]
@slorello89,
Thankyou for your help its working also want to confirm for SendAnSMS API I need to use "NexmoSmsResponseException" am I?.

**Comment by slorello89** [comment]
Hi @sejapsit - really glad to hear it's working - yes [NexmoSmsResponseException](https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/Messaging/NexmoSmsResponseException.cs) is the correct error.

**Comment by sejapsit** [comment]
Thankyou @slorello89
