### ISSUE TITLE
RsaUsingSha alg expects key to be of AsymmetricAlgorithm type.

### ISSUE THREAD

**Issue by Pandolfou** [Nexmo/nexmo-dotnet#22]
Hi,

I'm testing the Voice Api to possibly implement it in my application. I got an issue with the Call.Do() method (see attach file)
![screenshot_1](https://cloud.githubusercontent.com/assets/8547177/22268036/f85133e6-e253-11e6-9cd2-3dd7760a7378.jpg)

I'm not sure if I use the private key correctly:
I create a Nexmo application, save the private key from the response in a text file, add the applicationId to appsettings.json file that contain the file path of my private key.

I'm using the latest stable version of Nexmo.Api and jose-jwt.

Thank's for your help!

**Comment by smithrobs** [comment]
You are seeing this error because the Nexmo API switched from providing PKCS#1 formatted keys during application creation to PKCS#8. This library currently expects PKCS#1.

You can get around this with `openssl` as it will automatically convert it for you:

```
openssl rsa -in <KEY FILENAME> -out <OUTPUT KEY FILENAME>
```

I will update the library accordingly soon! Thank you for your patience. 😄

**Comment by Pandolfou** [comment]
Thank you! I'm glad to know that you know where the problem comes from :)

**Comment by smithrobs** [comment]
@Pandolfou I just pushed 2.2.0-rc2 to NuGet, which fixes this issue. I expect to release 2.2.0 in the next few days, but if you need this ASAP please pull down the pre-release version from NuGet.

**Comment by Pandolfou** [comment]
Nice, I will check that this week!

**Comment by leggetter** [comment]
> You are seeing this error because the Nexmo API switched from providing PKCS#1 formatted keys during application creation to PKCS#8. This library currently expects PKCS#1.

@smithrobs from your records, when did this switch take place?

**Comment by smithrobs** [comment]
@leggetter I'm not entirely sure. It was definitely working 12/7/16 (testing for 2.1.2 release). I don't have any records of generating a new application ID (when the user would receive a new key) until addressing this bug on 1/24/17, so sometime in between. Sorry I don't have anything more specific. If it were me, I would work backward from 1/24.

**Comment by pkopchik** [comment]
I am having this same problem using the Nexmo.Api and have built the project locally, upgrading it to a Visual Studio 2017 project. I have tried the conversion of the private key and go my finger on the offending line of code. I have gotten past that but not in a way that works so first see this: 
![nexmoapi jwt error](https://user-images.githubusercontent.com/29332178/27150974-1d8d4ac8-5117-11e7-9fe2-90ce14d93be7.PNG)

**Comment by pkopchik** [comment]
After some wrangling with the code, I simply updated the jose-jwt package to v2.3.0 (noticed that the v.2.0.0 was "not available in this source") and voila! It worked with the PKCS#8 key I had created using the Node.js app. At any rate thanks to Git.Hub for being here and Nexmo support for redirecting me to what I already found here.

**Comment by smithrobs** [comment]
@pkopchik Interesting! Thank you for documenting your fix. I will update the reference, test, and push out a new version to NuGet.

**Comment by gilbert031693** [comment]
I am having the same problem using nexmo voice api my jose-jwt package is v2.3.0 but I got this error on the image below. I also tried to update v2.4.0 unfortunately nothing happens. 

![rs256](https://user-images.githubusercontent.com/33366228/32431266-c905d5a6-c30d-11e7-9e5c-3a889f3725d1.jpg)

**Comment by smithrobs** [comment]
@gilbert031693 Would you provide the version of Windows and .NET that you are running when you receive this exception?

**Comment by gilbert031693** [comment]
@smithrobs  I'm running .Net 4.5.2

**Comment by gilbert031693** [comment]
Hi @smithrobs also trying Nexmo this I got an issue with the Call.Do() method, kindly attached image for your reference. 
![image pasted at 2017-11-8 10-20](https://user-images.githubusercontent.com/33366228/32528534-79e841b8-c46e-11e7-8b61-6c094a6d94fd.png)

**Comment by smithrobs** [comment]
@gilbert031693 I have received reports in the past of issues with the `RSACryptoServiceProvider` in 4.5.2. Is there any way you can try your code with a different framework version like 4.6.x?

**Comment by BloomBitz** [comment]
Hey i got the HTTP response 201 after execute outbound call but client did not get any call. Any suggestion?
