### ISSUE TITLE
Issue with ASP .NET MVC apps [web.config]

### ISSUE THREAD

**Issue by sidsharma27** [Nexmo/nexmo-dotnet#23]
Was able to replicate this issue - was not getting SMS with ASP .NET MVC web app

Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.RemoteDependency","time":"2017-01-25T06:32:01.1398441Z","tags":{"ai.internal.sdkVersion":"rddf: 2.0.0.25000","ai.device.roleInstance":"DESKTOP-IDL5ST6"},"data":{"baseType":"RemoteDependencyData","baseData":{"ver":2,"name":"https://rest.nexmo.com/sms/json?from=14086507102&to=14083915411&text=this+is+a+test&api_key=&api_secret=&","id":"R2Szr4r7hA8=","value":265.1641,"resultCode":"200","dependencyKind":1,"success":true,"properties":{"DeveloperMode":"true"}}}}

Able to get SMS when running a console app [app.config]

**Customer request:

> I am now testing Nexmo using nuget - https://github.com/Nexmo/nexmo-dotnet <https://github.com/Nexmo/nexmo-dotnet>. I’ve done the things in readme wiki there and I’ve set up web.config to have: 
> 
> <add key="Nexmo.UserAgent" value="myApp/1.0" /> 
> <add key="Nexmo.Url.Rest" value="https://rest.nexmo.com <https://rest.nexmo.com/>" /> 
> <add key="Nexmo.Url.Api" value="https://api.nexmo.com <https://api.nexmo.com/>" /> 
> <add key="Nexmo.api_key" value="cfx4578x" /> 
> <add key="Nexmo.api_secret" value="271x7585a661c06x" /> 
> 
> And this is the code to send “testing sms nexmo” to my number from my number: 
> 
> var results = SMS.Send(new SMS.SMSRequest 
> { 
> from = “639369907343”, 
> to = “639369907343”, 
> text = “testing sms nexmo” 
> }); 
> 
> After execution, results.messages.error_text has value “Missing username” (where/how can I set username? I don’t think I know my username, unless it’s the login I use to access my account in nexmo.com <http://nexmo.com/>) 
> 
> So I went and found same probem and I notice that this forum: https://github.com/Nexmo/nexmo-dotnet/issues/17 <https://github.com/Nexmo/nexmo-dotnet/issues/17> 
> 
> Has a fix and says to configure the file: appsettings.json to copy always in the output directory. Problem is, my project doesn’t have this file, appsettings.json, as I am using plain aps.net/mvc <http://aps.net/mvc>; I think asp.net <http://asp.net/> core is using appsettings.json. so, how do I proceed testing**

**Comment by smithrobs** [comment]
I need to make another attempt at explaining how configuration works in the README as this is a consistent point of confusion. There are a few facts in play here:
- .NET Framework (**not** Core) templates in Visual Studio and in general make use of XML-based web.config and <application executable>.config configuration files.
- .NET Core templates, yeoman generators, and in general make use of JSON-based configuration files. The convention used to be `settings.json` but somewhere around the .NET Core 1.1 release changed to `appsettings.json`. The library followed suit.
- In the interest of trying to make everything "just work", the library looks for configuration files in a particular order per the README, favoring the JSON versions over the XML configuration.
- Version 2.2.0 of the library (which is still in pre-release - I expect to promote it to release in the next few days) has configuration logging. In this instance, the user (if they chose to enable logging) would be informed that configuration was not found.
- Issue #17 is outstanding - I have yet to find a good way to get the hosting environment path when the library is used in a hosting environment. The "fix" is to know exactly where to manually place the config file.

For this specific support request, their configuration file is not being found. They can create a `appsettings.json` file by following the example in the README. Also, they may want to try logging with 2.2.0-rc1 via NuGet:
```Install-Package Nexmo.Csharp.Client -Pre```
and follow the README instructions to place a `logging.json` file in the same location as the aforementioned `appsettings.json`. Then they will have confirmation as to whether configuration was found or not.

**Comment by sidsharma27** [comment]
Adding an 'appsettings.json' is the fix for this issue. However, on the readme it says web.config should work but ASP .NET Standard MVC web apps are not able to use the CL when credentials are stored in the 'web.config' file. This should be removed or web.config should be able to store credentials as multiple instances of this issue have been reported.

**Comment by smithrobs** [comment]
I'd hate to remove the ability to configure via `web.config`, but it's the biggest source of issues for the library. I was hoping Microsoft would build out functionality I could use to address #17 but with the RTM release due in less than a month, I will figure out another path. It might end up being the removal of `web.config` support.

The core issue is that `web.config` has to be in a specific directory which is dependent on how the web application is invoked.

**Comment by smithrobs** [comment]
I have made the decision to remove `web.config` support in v3.0. The reasoning will be explained in the change log. Thanks for the feedback.
