### ISSUE TITLE
Using Custom SenderID for outbound SMS

### ISSUE THREAD

**Issue by PrimaShella** [Nexmo/nexmo-dotnet#24]
Do I need to add more applicationsetting.json or code if I want to use a custom SenderID ?
assuming I have purchased the SenderID
here is my code :
```
string PhoneNo = "081375840392";
string SenderID = "CUSTOM";
var results = SMS.Send(new SMS.SMSRequest
{
       from = SenderID,
       to = PhoneNo,
       text = "Test Sms"
});
```

**Comment by smithrobs** [comment]
You do not need to add anything else to `appsettings.json` (note it must be named that or one of the other filenames specified in the README) except API credentials. Everything else is up to you, including providing a proper SenderID/from. 😄

**Comment by PrimaShella** [comment]
thank you very much 😄
