### ISSUE TITLE
Solution does not build in either VS2015 Update 3 or VS2017 RC4

### ISSUE THREAD

**Issue by stephen-riley** [Nexmo/nexmo-dotnet#26]
I tried both of them, stock.  Neither builds at all.

Recommend updating README.md to reflect more detailed build instructions?

**Comment by smithrobs** [comment]
Would you be able to provide an error list or compile log for the VS2015 update 3 scenario along with your version(s) of .NET Framework, .NET Core, and VS installed?

You would need the following frameworks installed to have a "green" build:
- net452
- net46, net461, net462
- netstandard1.6 (.NET Core 1.0 LTS recommended)

I have tested with VS Enterprise v14.0.25431.01 Update 3 with the above frameworks installed and have no issues, so I would love to get feedback from others having issues with a similar setup. Ref'ing #11 as well - I need to look into a CI solution.

I haven't tested with a VS2017 environment (hence why it is not yet in the README) but would appreciate an error list or compile log from that as well. I think VS2017 releases today - I will look into getting an environment setup.

**Comment by smithrobs** [comment]
referencing #28 for VS2017 conversion

**Comment by smithrobs** [comment]
Updated build support in the `3.0` branch. Per the README:

- 4.5.2
- 4.6, 4.6.1, 4.6.2
- .NET Standard 2.0

Visual Studio 2017 is required (Community is fine). v15.3.5 is recommended.

Closing this as it's going on 6 months old and VS2017 (3.0 branch of this lib) seems to be working for others (@RabebOthmani ?). I'd be happy to revisit if needed.
