### ISSUE TITLE
Allow runtime configuration and do away with static implementation

### ISSUE THREAD

**Issue by JohannesEH** [Nexmo/nexmo-dotnet#29]
Currently the library has a very limited way of being configured. Namely through a set of predetermined .config or .json files. It would be better if this configuration was more open to being specified at runtime. This would allow settings to come from environment variables, or being loaded from a custom data store.

Also please open up the logging configuration as well.

**Comment by smithrobs** [comment]
As of 2.2.0, you can do logging per [the README](https://github.com/Nexmo/nexmo-dotnet#logging) - please let me know or submit a PR if you would like to see more or something different.

Thank you for the feedback regarding configuration - this is a hot topic for the next version. We are discussing steps to move in this direction. Did you have a specific data store in mind?

**Comment by JohannesEH** [comment]
Can you elaborate a little on the reasoning behind the current implementation?

**Comment by JohannesEH** [comment]
I mean, why make the configuration class sealed, and why use a singleton instance?

**Comment by smithrobs** [comment]
If pressed for rationalization, I suppose I would say: We have users that make use of the JSON and XML configurations. The sealed class is there because it wouldn't make sense (in my opinion) for any code to inherit from it. The singleton was simple to implement and makes it easy to enforce optional request throttling across the consuming app. I'm quite open to suggestions, and as mentioned above we are looking into improvement in this area for the next release.

That said, I am much more interested in hearing how you (as a consumer of the library) would like to use it in production.

**Comment by JohannesEH** [comment]
Fair enough.

Well I cloned the source and had a look. My first comment is that the entire thing is static. 👎 This is an issue for your consumers (at least for me) as it will not allow them to inject your library using dependency injection. My second gripe is that the transport classes are using inconsistant .net naming like "SMS.network_code" or "NumberUpdateCommand.voiceCallbackValue". Why not go the extra step and use the regular .net naming "Sms.NetworkCode" and "NumperUpdateCommand.VoiceCallbackValue"? The same goes for enums.

I my perfect world I would like the library to consist of injectable service classes, no public nested classes/enums and a consistent .net-ified naming scheme. Like :

```csharp
namespace Nexmo
{
  public abstract class ConfigurationBase
  {
    public ILogger Logger { get; set; }
    public string ApiKey { get; set; }
    public string ApiSecret { get; set; }
    /* snip... */
  }
  
  public sealed class DefaultConfiguration : ConfigurationBase { /* snip */ }

  namespace Application
  {
    class ApplicationService
    {
      ApplicationService() : this(new DefaultConfiguration())
      ApplicationService(Configuration config) { /* snip */ }
    }

    class ApplicationRequest
    {
      public string AnswerUrl { get; set; }
    }

    // application service transport classes like ApplicationRequest/Response etc.
  }

  namespace Sms
  {
    class SmsService { /* snip */ }
  }

  // etc...
}
```

Using a structure like this it would make my day a lot easier. Not only would classes be easier to find, but it would also mean that I could configure and inject the library whichever way I wanted.

You mentioned that you think it is nice that you get to decide the throttling parameters. I get that, but that only works if people are using your library to begin with. You could still implement something throttle helper but I don't see why you would force users to use your implementation. Make it the default but make it configurable. For instance it says on your [support page](https://help.nexmo.com/hc/en-us/articles/203993598-What-is-the-Throughput-Limit-for-Outbound-SMS-) that custom throttle limits can be negotiated by contacting yuor account manager. However, your library doesn't allow its consumers to fiddle with the throttle implementation as it is.

**Comment by smithrobs** [comment]
- Re: DI and singleton usage - We hear you loud and clear. I'm not one for defending decisions made in the past (almost 2 years now) as I cannot change that, but the present/future is something we can alter. 😄 
- Re: inconsistent naming - Agreed. We have to strike a balance of not breaking user's existing code while improving the library. Both this and other breaking improvements like removing/augmenting the singleton pattern are things to look for in v3.
- One thing to note that may _slightly_ assist you in 2.2.0 is you may override credentials for each call. You may also directly make custom requests to the Nexmo API via `ApiRequest.DoRequest` etc.
- I find "forced" is too strong of a word in the case of throttling. 😄 Per the spec (more on that in a sec), the library's rate limiting is optional via configuration and disabled by default. The user is able to configure the requests per second as needed. I believe there are also server-side checks/monitoring but that of course is not the library's responsibility.

For a bit of history, this library was written way before [we had a cross-language spec](https://github.com/Nexmo/client-library-specification) and there are still items that need to be addressed and improved upon. For instance "MUST not force a singleton (but may provide access to a singleton)." is in the spec, so rest assured it's going to change.

**Comment by JohannesEH** [comment]
Thanks Rob, I was a little tired when I wrote the last comment, so I might have come of as a little cranky or too strong. Nexmo is a good service and I'm just eager to use it. :)

The cross-language spec is a good start, and I hope that v3 of the client library is more in line with the spec. You will have to break library consumers code no matter what, if you have to follow the spec. So, please consider to do the restructuring and renaming as part of v3, so the library follows the goal of the spec:

> The goal of this document is to make all Nexmo Client Libraries have a similar feel, *while still adopting the standard practice and usage of each individual language*.

Using ApiRequest might help a little (at least with authentication), but I think I'd rather roll my own for now while you still support key/secret auth.

**Comment by smithrobs** [comment]
@dpihac @billbgarland @VagyokC4 @JohannesEH Sorry to mention y'all again, but I would love to get real user feedback and involvement with 3.0. If you have any additional suggestions around the code and capabilities for 3.0, please either comment in here or create a separate issue to discuss. Feel free to reach out on the Slack as well.

**Comment by dpihac** [comment]
Hey @smithrobs, thanks for update. I will test 3.0 sometime this week and let you know how it goes. Thanks for pushing it to NuGet!

**Comment by dpihac** [comment]
@smithrobs I successfully tested 3.0 prerelease in LINQPad - test scenario worked well so I'll be pushing this to production (sending SMS from the Airtable table). I'm not sure if there are any issues that would prevent me from doing so?

**Comment by smithrobs** [comment]
@dpihac Good to hear! The only issue is that since it's a pre-release, the code will likely change between now and 3.0 stable. The [3.0 milestone](../milestone/3) has a current representation of what may change. You may then need to change your code to move to 3.0 stable.

**Comment by smithrobs** [comment]
v3.0 is out! Closing this as instance configuration is now supported. Thanks for everyone's feedback.
