### ISSUE TITLE
Security Exception on live server only

### ISSUE THREAD

**Issue by Benjamin1973** [Nexmo/nexmo-dotnet#32]
I successfully sent messages from my development computer, but on live server an exception is thrown:

_System.TypeInitializationException: The type initializer for 'Nexmo.Api.Configuration' threw an exception. ---> System.Security.SecurityException: Request failed. at Nexmo.Api.Configuration..ctor() at Nexmo.Api.Configuration..cctor() --- End of inner exception stack trace --- at Nexmo.Api.Request.ApiRequest.GetBaseUriFor(Type component, String url) at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds) at Mailer.Button_SendMail_Click(Object sender, EventArgs e)_

I'm using a project targeting .NET 4.52 and current nexmo-dotnet installed via Nuget, and I'm attempting only sending SMS.

**Comment by smithrobs** [comment]
Is this an ASP.NET web application? If so, do you know what trust level the web application is running at in production?

We haven't tested anything other than full trust - without testing, I would guess anything less than high trust will not work.

**Comment by Benjamin1973** [comment]
Nice call.

I'm testing Nexmo on a Godaddy hosted site, and the default trust level was set to "medium."  Problem fixed, message successfully sent.

**Comment by smithrobs** [comment]
As netcore has deprecated CAS and trust levels and 3.0+ have removed `System.IO.File` usages, I am closing this without any further action.

Feel free to comment/reopen if anyone runs into an issue related to this.
