### ISSUE TITLE
Unicode?

### ISSUE THREAD

**Issue by Benjamin1973** [Nexmo/nexmo-dotnet#33]
My first messages in Korean were received with broken characters.  So I tried adding `type = "unicode"` to my SMSRequest.  It didn't throw an exception, but the message never went out (or at least it wasn't ever received).  Same thing happened if I tried a garbage type "uniasdfoiasdfoisa" or whatever.

When I try to use URLEncoding a plain text message a la https://docs.nexmo.com/messaging/sms-api/api-reference, it just sends out the escape codes as text rather than as Unicode characters.

Can you please tell me what I'm doing wrong?

**Comment by smithrobs** [comment]
This works for me on Win + netcore:

```csharp
SMS.Send(new SMS.SMSRequest
{
    from = "15554441212",
    to = "15554441213",
    type = "unicode",
    text = "SMS ☺☕✌ ㄱㅞㄶ한ᅓㅂ" // random unicode
});
```

Try that first and let me know.

Feel free to contact me on the [Nexmo slack](https://nexmo-community-invite.herokuapp.com/) for a bit more real-time communication if you'd like.

**Comment by smithrobs** [comment]
(from Slack) Additional test cases that worked for me in Win/.NET Framework 4.5.2 from US Nexmo # to US test cell #
```
"강서현 must register by Thursday, May 11, 2017"
"강서현 must register by Thursday, May 11 2017"
"강서현 must register by Thursday, May 11 2017th and this is really the last chance!"
"강서현 must register by May 11, 2017, and this is really the last chance!"
```
Doesn't seem to be a library issue. Leaving this open for now as @Benjamin1973 is going to contact Nexmo Support for further assistance.

**Comment by smithrobs** [comment]
Closing; identified as not a library issue.
