### ISSUE TITLE
Update readme and examples for 3.0

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/nexmo-dotnet#35]

**Comment by RabebOthmani** [comment]
@smithrobs should the targeted frameworks be on a separate section as the supported frameworks is a recurrent question?

**Comment by smithrobs** [comment]
That's a good idea, yeah. It doesn't make much sense to have it in the "Contributing" section.

Not to put more on someone else's plate, but I'd rather someone other than me take a deeper look at the documentation as I feel I'm too close to the code at times to see the gaps...

**Comment by RabebOthmani** [comment]
I'm happy to do that, I'll look at readme and the examples. Once v3 is released, I'll also be able to work on the documentation for developer.nexmo.com
