### ISSUE TITLE
Support .NET Standard 2.0/Core 1.1

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/nexmo-dotnet#37]
Ensure everything works with .NET Standard 2.0/Core 1.1/2.0

- [ ] Address breaking `Microsoft.Extensions.DependencyInjection` change ([details](https://github.com/aspnet/DependencyInjection/issues/550))

**Comment by khaledelmahdi** [comment]
Any update? .NET 2.0 has been released already.

**Comment by smithrobs** [comment]
Still working on it - I'm on a push to get another v3 pre-release out by end of month. I'll see if I can expedite Standard/Core 2.0 support.

**Comment by wgpsutherland** [comment]
Hi, is there any update on when support for .NET 2.0 will be available?

**Comment by smithrobs** [comment]
I just published pre2 that moves from 1.6 to 2.0. I was able to ref and use this with Core 2.0. Please test and let me know if you run into any issues. Thanks!

**Comment by fmonroe** [comment]
Hi. I just posted on the Slack channel. I have this issue. ASP.NET Core 2 , 3.0.0-pre2, VS2017. Is there something I am missing? Thanks.

**Comment by smithrobs** [comment]
@fmonroe Thank you. I just published 3.0.0-pre3 that fixes the ASP.NET Core 2 Microsoft.Extensions.DependencyInjection change for real this time.

netstandard1.6 is built against Microsoft.Extensions.DependencyInjection v1.0.2 - use this for ASP.NET Core 1
netstandard2.0 is built against Microsoft.Extensions.DependencyInjection v2.0.0 - use this for ASP.NET Core 2

I'm only using the built-in DI for logging, so I'd like to see this converge at some point before the official v3.0 release.

**Comment by fmonroe** [comment]
WoW! It's now working as expected. Thank you for the quick turnaround. I love this Api. :)
