### ISSUE TITLE
You must provide at least one type of authentication via configuration! on Asp.net Core 1.1.2

### ISSUE THREAD

**Issue by deepamalikworldpay** [Nexmo/nexmo-dotnet#38]
Vs Studio 2017
Asp.net Core 1.1.2
Nexmo Csharp Client 2.2.2

Api key,secret and from number are from account settings 

Code below for sending sms

                 SMSRequest s = new SMS.SMSRequest();
                s.from = "111111111";
                s.to = "11111111";
                s.text = "hello from web api asp.net ``core";`
                Nexmo.Api.Request.Credentials c = new Nexmo.Api.Request.Credentials();
                c.ApiKey = "apikey";
                c.ApiSecret = "apisecret";
                SMS.Send(s, c);

Throws Error 
 {System.ArgumentException: You must provide at least one type of authentication via configuration!
at Nexmo.Api.Configuration..ctor()
at Nexmo.Api.Configuration..cctor()}

**Comment by smithrobs** [comment]
Would you try this with the [3.0.0.-pre1](https://www.nuget.org/packages/Nexmo.Csharp.Client/3.0.0-pre1) nuget package? That removes the requirement for config files.

```Install-Package Nexmo.Csharp.Client -Pre```

**Comment by deepamalikworldpay** [comment]
It worked.
Thanks,
Deepa
