### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/nexmo-dotnet#4]
- [X] Update Newtonsoft.Json
- [X] Move away from ConfigurationManager
- [X] Switch to HttpClient
- [X] Replace usage of System.Web.HttpUtility.UrlEncode
- [X] Convert voice call sample app
- [X] Update solution/projects
- [X] NuGet package
- [x] Convert Sample web app
- [x] Test projects are still .csproj due to lack of nunit support

**Comment by jayrulez** [comment]
How is this going?

**Comment by smithrobs** [comment]
It's going 😄 Tentative release by 10/31.

**Comment by smithrobs** [comment]
A pre-release version (2.0.0-rc1) from the netcore branch with .NET Standard 1.6 support is on NuGet!

I will do some testing with OS X and Linux in the next few days.

**Comment by smithrobs** [comment]
NUnit support for .NET Core is available, but I'm having an issue getting the test runner to execute. I'll take another look at it after v2.2.0 is released.

**Comment by smithrobs** [comment]
Tests are (mostly) working in the 3.0 branch. There are still some inconsistencies that will be resolved before the non-pre 3.0 release.
