### ISSUE TITLE
Web Config Not Working in v2.2.2

### ISSUE THREAD

**Issue by kentplaza** [Nexmo/nexmo-dotnet#42]
I am using v2.2.2. the api and key_secret must place in appsettings.config? It work if i place in appsetting but not in web.config.

But saw the doc mention it will read the config file by precedence.
![image](https://user-images.githubusercontent.com/9535716/29349290-85941606-828b-11e7-8bf3-cf95de278cb2.png)

Can I place in web.config cause I hope my api key can place in same place for my solution.

**Comment by smithrobs** [comment]
You can place the credentials in `web.config`. The library can have issues getting the path to web.config correctly, but if you're using .NET Framework on Windows you should be fine.

I do want to let you know that v3.0 will have no built-in configuration support. You will need to provide your API key and secret to the client instance and methods on your own. There is a 3.0-pre NuGet package if you want to try that out or have issues with the v2.2.2 configuration.
