### ISSUE TITLE
list of issues to look at while contributing to the code

### ISSUE THREAD

**Issue by rajanadar** [Nexmo/nexmo-dotnet#5]
hey @smithrobs 

is there an issue list (ordered/unordered) that we can look at and contribute PRs pertaining to that?
what is the recommended way?

please let me know.

thanks,
Raja

**Comment by smithrobs** [comment]
Hi @rajanadar! There is a list of things I'd personally like to improve, yes... but right now they're only inside my brain :) I'm finishing up the new voice API calls for a v2 release and then will be adding .NET Core support.

If you have something specific in mind and want to chat before submitting a PR, feel free to DM me on twitter [@smithrobs](https://twitter.com/smithrobs). I'm always open to PRs that improve the project and adhere to the [Nexmo guidelines](https://github.com/Nexmo/client-library-specification)

**Comment by rajanadar** [comment]
don't have anything specific in mind. just wanted to know if there is a list of items, that i can look at and maybe do something. :) anyways, i'll check from time to time, and take it from there.

**Comment by smithrobs** [comment]
@rajanadar I just put in a few of the items I could think of. Let me know if anything sounds interesting to you; I'd be happy to work with you (or anyone) on a PR!

**Comment by rajanadar** [comment]
thanks @smithrobs 

am traveling for the next 2-3 weeks. will go through the list and try to grab one when back.
looking at some of the items, one of them is around logging.. have added some of my thoughts around it..
