### ISSUE TITLE
Implement `listNumbers`

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-dotnet#50]

**Comment by smithrobs** [comment]
@judy2k Is [the current Account.Numbers method](https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/Account.cs#L158) missing something specific? I'll take a closer pass when I go about implementing the rest of these issues.

**Comment by RabebOthmani** [comment]
confirming what @smithrobs mentioned, this is already implemented. @judy2k are you happy with the implementation? Can we get rid of this issue? Thanks

**Comment by judy2k** [comment]
I raised this issue based on the feature spreadsheet we have internally at Nexmo. Closing.
