### ISSUE TITLE
Implement `linkNumber`

### ISSUE THREAD

**Issue by judy2k** [Nexmo/nexmo-dotnet#51]

**Comment by smithrobs** [comment]
Part of call-tracker, see [this for details](https://developer.nexmo.com/tutorials/call-tracking#link-phone-numbers-to-the-nexmo-application) and [this for implementation](https://github.com/Nexmo/nexmo-cli/blob/master/src/request.js#L219).

**Comment by judy2k** [comment]
@smithrobs This looks like this feature has been implemented as part of NumberUpdateCommand. Can you confirm?

**Comment by RabebOthmani** [comment]
@judy2k closing issue as feature has been implemented 
https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/Number.cs#L121-L126
