### ISSUE TITLE
WPF configuration issue

### ISSUE THREAD

**Issue by cataliz3er** [Nexmo/nexmo-dotnet#58]
How do you configure Nexmo for WPF applications. Where exactly in the app.config file should the <appSettings> be placed? 
I placed it in the <Configuration> tag, and I get an Argument Exception: You must provide at least one type of authentication via configuration! when I call SMS.Send(...).
Thanks!

**Comment by smithrobs** [comment]
Hey @cataliz3er - you are better off trying one of the v3.0.0 pre-releases. We are moving away from handling configuration-via-files in the library to **your code** providing credentials as you see fit. Let me know if this is a problem or if you have any questions.

Example usage via v3.0:
```csharp
var creds = new Nexmo.Api.Request.Credentials {
    ApiKey = "KEY",
    ApiSecret = "SECRET"
};
var client = new Client(creds);
```

**Comment by cataliz3er** [comment]
The type or namespace name 'Client' could not be found.
I installed the API via Nuget.
Tries passing creds as parameter to SMS.Send()
![capture nexmo 3](https://user-images.githubusercontent.com/16380896/30811744-c452d008-a211-11e7-8f16-c889d77d3c58.PNG)

**Comment by smithrobs** [comment]
How about something like this example?

1. Install v3.0.0-pre2

`Install-Package Nexmo.Csharp.Client -Version 3.0.0-pre2`

2. Use something like the code below:
```csharp
using Nexmo.Api;

namespace Nexmo.Samples.Coverage
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var creds = new Nexmo.Api.Request.Credentials {
                ApiKey = "KEY",
                ApiSecret = "SECRET"
            };

            // both execution methods work:
            var client = new Nexmo.Api.Client(creds);
            client.SMS.Send(new SMS.SMSRequest{
                from = "NEXMO NUMBER",
                to = "YOUR NUMBER",
                text = "hey there!"
            });

            SMS.Send(new SMS.SMSRequest{
                from = "NEXMO NUMBER",
                to = "YOUR NUMBER",
                text = "hey there!!!"
            }, creds);
        }
    }
}
```

**Comment by smithrobs** [comment]
Also I encourage anyone using Nexmo to join the Nexmo Slack - there's always someone (like me) around to help out usually in real-time: https://developer.nexmo.com/community/slack

**Comment by cataliz3er** [comment]
Works! Thanks a lot!

**Comment by leggetter** [comment]
@smithrobs @RabebOthmani - I love the `Nexmo.Api.Client` 🙌
