### ISSUE TITLE
Cant send sms in UAT but same code working fine in DEV Envoirnment

### ISSUE THREAD

**Issue by amitkaushal80** [Nexmo/nexmo-dotnet#60]
When I am trying to send the sms in UAT i am getting the following Exception
System.TypeInitializationException: The type initializer for 'Nexmo.Api.Configuration' threw an exception. ---> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'. at Nexmo.Api.Configuration..ctor() at Nexmo.Api.Configuration..cctor() --- End of inner exception stack trace --- at Nexmo.Api.Request.ApiRequest.GetBaseUriFor(Type component, String url) at Nexmo.Api.SMS.Send(SMSRequest request, Credentials creds) at EmailClient.Sms_Nexmo.sendMessage(String message, String ClientPhoneNumber, String postback, Boolean isPostBack) in C:\Users\Amit.Kaushal\Documents\MyWorking\TFS_WorkSpace\EmailClient\EmailClient\Sms_Nexmo.aspx.cs:line 380

Following is the code how i try to send the sms

var result = Nexmo.Api.SMS.Send(new Nexmo.Api.SMS.SMSRequest
                    {
                        from = "12264588135",
                        to = ClientPhoneNumber,
                        text = message,
                    });

My appsettings.json file looks like 
{
  "appSettings": {
    "Nexmo.UserAgent": "myApp/1.0",
    "Nexmo.Url.Rest": "https://rest.nexmo.com",
    "Nexmo.Url.Api": "https://api.nexmo.com",
    "Nexmo.api_key": "xxxxxxxxx",
    "Nexmo.api_secret": "2xxxxxxxxf",
    "NEXMO_FROM_NUMBER": "1xxxxxxxx5 "

  }
}

I keep the json file to the same place where i copied .dll and .pdb files in UAT

**Comment by smithrobs** [comment]
- Which version of the Nexmo C# library are you using? v2.2.2 or a v3.0.0-pre release? I assume v2.2.2 but want to be sure.
- Does the .NET Trust level differ in UAT from your dev environment? v2.2.2 requires at least `High` trust.

**Comment by amitkaushal80** [comment]
Yes .net version is v2.2.2 in both Dev enviornment and UAT

**Comment by amitkaushal80** [comment]
.Net Framework is 4.6.1 and Nexmo C# library v2.2.2 in both UAT and Dev

**Comment by amitkaushal80** [comment]
Trust Level in UAT is Full

**Comment by smithrobs** [comment]
Thank you for the information. Let me see if I can reproduce this.

In the meantime, since the stack trace indicates this is happening in the Configuration class, you may want to try v3.0.0-pre:

`Install-Package Nexmo.Csharp.Client -IncludePrerelease`

This removes the file-based configuration entirely and lets you (the library consumer) manage and pass in credentials as you see fit.

**Comment by amitkaushal80** [comment]
I just noted that version in UAT is 4.5.50709 and in development 4.6.01590. Should i update .net in UAT before trying v30.0-pre.

**Comment by smithrobs** [comment]
Interesting. Disclaimer: I try not to give out too much environment advice as it's tricky to get 100% right, but if that is true then I would say yes, try updating your UAT.

4.6.01590 is .NET 4.6.2
4.5.50709 is .NET 4.5 RTM which I don't know how/if it would run an app targeted for v4.6.1.

Please let me know if doing this addresses your question. Thanks!

**Comment by amitkaushal80** [comment]
can i downgrade the .net version to 4.5 RTM in Development?. Will nexmo work on that ?

**Comment by smithrobs** [comment]
Unfortunately, you would have to pull the library source and build on your own for reasons described in [this issue](https://github.com/Nexmo/nexmo-dotnet/issues/3). v4.5 is no longer supported by Microsoft and therefore we do not officially support it either. You **can** update to v4.5.2 which **is** targeted by the NuGet package.

**Comment by amitkaushal80** [comment]
Thank alot for your help. After updating to .net 4.7 it is working fine.
 I have one more question-  can we associate the each sms with user information like appointmentid, so that when user respond to that particular message we can check which user replied which sms (or which appointmentid)

**Comment by smithrobs** [comment]
@amitkaushal80 You will want to use the `client-ref` property referenced [in the docs here](https://developer.nexmo.com/api/sms#parameters). You will need to email support@nexmo.com to enable this for your account.
