### ISSUE TITLE
Consolidate .NET Framework support

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/nexmo-dotnet#61]
See https://blogs.msdn.microsoft.com/dotnet/2017/09/28/net-framework-4-7-1-runtime-and-compiler-features/

4.6.1, 4.6.2, 4.7, 4.7.1 could all be serviceable from netstandard2.0

**Comment by slorello89** [comment]
framework support has been moved to 4.5.2, 4.6 and .net standard 2.0 - thus I'm closing this issue.
