### ISSUE TITLE
Call.Do(comand) - production error

### ISSUE THREAD

**Issue by pmaxim** [Nexmo/nexmo-dotnet#64]
I have a voice call on my computer. When placed in production (Windows IIS).
The file private.key finds successfully, but gives an error "Value cannot be null.
Parameter name: value"
The file *.key created:
1. Nexmo.Api.Application.Create(appRequest, cr);
2. nexmo app:create
3. site
In all cases, the same error
Tell me what could be the problem?
Thanks
Maxim (Kiev, Ukraine)

**Comment by smithrobs** [comment]
Thank you for your patience. You may receive this error when Nexmo rejects your call request - I tend to get this when I forget I've changed my Nexmo phone number. Check your "from" number (and your "to" just in case). The "from" must be Nexmo and the "to" must accept the call. Let me know if you still have this issue or if verifying your "from" addresses this.

**Comment by pmaxim** [comment]
Thank you. I corrected this mistake. It was required to close static files in ANSI format (Visual Studio - Json files UTF-8).
I now have 2 new problems:
1. The software created by the NCCO does not work.  For example ApiController return model.
2. Static files work. But when calling from a virtual phone NEXMO to an American mobile phone - on it the calling number is displayed as Unknown.

**Comment by smithrobs** [comment]
👍 Ah, yes - the encoding issue is something that needs fixed as a part of #8 . Thanks for the feedback.

#1 - I will take a look at the NCCO issue separately.
#2 - Check out this [support article](https://help.nexmo.com/hc/en-us/articles/204015273) and if that doesn't clear things up, please send your query to support@nexmo.com as they would be better able to assist you in this case.

Closing since it sounds like the original issue has been resolved.

**Comment by pmaxim** [comment]
Hello.
I have a problem preserved.


Call.Do(comand); calling number "unknown"


 var comand = new Call.CallCommand
      {
        to = new[]
        {
          new Call.Endpoint
          {
            type = "phone",
            number = Nexmo Virtual number "17022769530"
          }
        },
        from = new Call.Endpoint
        {
          type = "phone",
          number = American number
        },
        answer_url = new[]
        {
          nexmoName
        }
      };
Thanks
Maxim



27 октября 2017, 17:08:40, от Rob Smith <notifications@github.com>: 


👍 Ah, yes - the encoding issue is something that needs fixed as a part of #8 . Thanks for the feedback.

#1 - I will take a look at the NCCO issue separately.
#2 - Check out this support article and if that doesn't clear things up, please send your query to support@nexmo.com as they would be better able to assist you in this case.

Closing since it sounds like the original issue has been resolved.
