### ISSUE TITLE
Creating an NCCO Provider

### ISSUE THREAD

**Issue by pmaxim** [Nexmo/nexmo-dotnet#65]
Everything works when you use it https://nexmo-community.github.io/ncco-examples/first_call_talk.json
If I take this file from my site, the sound does not play
The software solution does not work either
 public HttpResponseMessage NexmoVoice()
      {
        var m = new List<TextModel>();
        var js = new TextModel
        {
          action = "talk",
          voiceName = "Russel",
          text =
            "You should not create json by your own, you can return an object from this method and make JSON as default format for returned data."
        };
        m.Add(js);
        var response = Request.CreateResponse(HttpStatusCode.OK, m);
        response.Headers.CacheControl = new CacheControlHeaderValue()
        { 
          MaxAge = new TimeSpan(0, 0, 10, 0)
        };
        return response;
    }
What is the problem?

**Comment by smithrobs** [comment]
This is more of a scenario/usage question - you should visit the [quickstart project here](https://github.com/nexmo-community/nexmo-dotnet-quickstart/tree/ASPNET/NexmoVoiceASPNetCoreQuickStarts) which serves NCCO and includes a [helper class](https://github.com/nexmo-community/nexmo-dotnet-quickstart/blob/ASPNET/NexmoVoiceASPNetCoreQuickStarts/Helpers/NCCOHelpers.cs) that might be of use.
