### ISSUE TITLE
ArgumentException: You must provide at least one type of authentication via configuration!

### ISSUE THREAD

**Issue by tsagld** [Nexmo/nexmo-dotnet#66]
It seems that the Nexmo configuration cannot find the appsettings.json containing the authentication parameters.
When my application starts, the Nexmo.Csharp.Client fails in the constructor of Nexmo.Api.Configuration, with the following exception:

**ArgumentException: You must provide at least one type of authentication via configuration!**

Things I tried:
* Move the json settings file into my Controllers folder (that is where Nexmo gets activated);
Didn’t help.
* Copy the relevant piece of the Configuration.cs from GitHub (where the authCapabilities are read) from the above link into my own code. The config settings are then read perfectly fine and no exception is thrown.

These are the settings from my appsettings.json:
{
"appSettings": {
"Nexmo.UserAgent": "NEXMOQUICKSTART/1.0",
"Nexmo.Url.Rest": "https://rest.nexmo.com",
"Nexmo.Url.Api": "https://api.nexmo.com",
"Nexmo.api_key": "….",
"Nexmo.api_secret": "….",
"NEXMOFROMNUMBER": "31612345678", #test account
"Nexmo.Application.Id": "…",
"Nexmo.Application.Key": "D:\\tmp\\Nexmo\\private.key"
}

**Comment by smithrobs** [comment]
I assume you are using v2.2.2? Could you try the v3.0 prerelease? v3.0 removes the need for file configuration and lets you handle it by yourself.

**Comment by tsagld** [comment]
I'll stick with 2.2.2....I found that moving the settings to the app.config solves the problem. I can stll reproduce the problem by using appsettings.json.

Thanks for the quick answer.

**Comment by smithrobs** [comment]
Thanks for the info and glad you found a resolution. Going to leave this open until v3.0 is released.

**Comment by gilbert031693** [comment]
Hi @smithrobs also trying Nexmo this I got an issue with the Call.Do() method, kindly attached image for your reference.
![image pasted at 2017-11-8 10-20](https://user-images.githubusercontent.com/33366228/32529156-de13d334-c471-11e7-98b8-bad0f26661f7.png)

**Comment by smithrobs** [comment]
v3.0 is out! Please try the release and feel free to reopen this issue if you are still having problems.
