### ISSUE TITLE
Errors throw a key cannot be found exception

### ISSUE THREAD

**Issue by jonHumphries** [Nexmo/nexmo-dotnet#68]
When an incoming message to the system is an error, a key cannot be found exception is thrown and the original message is hidden.  
While this ticket is for the .Net library, in the python version this was caused by an attempt to read the 'Direction' which is not part of the error schema.

This causes major problems in both development and production environments as we receive no error messaging and therefore are left to guess what the problem may have been.  Projects that should only take a couple of hours take days to identify and resolve.

**Comment by smithrobs** [comment]
I'm happy to ensure this is not an issue with the .NET library and will resolve it if needed. That said, which "incoming meesage" are you referring to? The Voice Call API? It [looks like it is present](https://github.com/Nexmo/nexmo-dotnet/blob/master/Nexmo.Api/Voice/Call.cs#L117) in the v2.2.2 code. 

Please help me out by describing exactly where/when you are receiving this exception by providing sample/pseudocode and/or the stack trace as well as the version of this library you are using. Thanks!

**Comment by jonHumphries** [comment]
Aloha,
    This is just in the voice api (as far as i know, we don't use the sms api).  It seems to be that anytime we submit an invalid request we get a Key cannot be found Error in Newtonsoft.Json.  The easiest scenario to duplicate is to have the wrong application id in the appsetting.json file.  Other scenarios where we don't get the correct error message from nexmo due to the key cannot be found error are more difficult to duplicate.  For example, we generated some 429's before and were not able to get those messages.  Its hard for me to list all the scenarios since we don't get the error messages.

We can't compile your .net library from code.  Not sure on your setup but we are on VS2015.  We were able to compile and run from the python library which doesn't tie into our production systems but did enable us to identify a line of code where the 'direction' property was being pulled from the incoming message and direction wasn't present with the error message, hence the "Key cannot be found" error.  Btw, I work with Jeff who has been messaging with you on slack if that helps.

**Comment by smithrobs** [comment]
Thank you; I will try to reproduce.

v2.x uses VS2015 Update 3 (community should be fine). If you have a moment and care to, feel free to open a separate issue with details on the build/compile error so I could correct it.

Say hi to Jeff for me! 😄

**Comment by jonHumphries** [comment]
Done,

Jeff says feel free to hit him up on slack 😉

Sent from Mail for Windows 10

**Comment by jonHumphries** [comment]
Any luck with either bug?

Sent from Mail for Windows 10

**Comment by smithrobs** [comment]
Is the original issue here that you receive a 401 Unauthorized but get a json deserialization error similar to the following?

```
System.ArgumentNullException was unhandled
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: value
  ParamName=value
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
...
```

If so, this ties in #7 where this library as a whole does a minimum job _at best_ in handling errors. Logging via `logging.json` can be a bit more helpful as you *will* see the 401 error in the log there.

Let me think a bit more about throwing something like an `AuthenticationException` in this scenario. Your input is welcomed as well: Would you be content with a more helpful exception? In your mind, would that close this issue?

**Comment by jonHumphries** [comment]
Yes that's the original problem.  When the results are deserialized and there is an error message ir sill looks for the ‘direction’ key even though that isn't part o the API, so a major bug. If yu tested to see if direction was present or handled errors differently from other requests, that would be fantastic.
As I understand it the logging requires staring at this console app which requires use of node.js.  I need  solution which logs errors in production.  Some of our issues have to do with concurrency and hardware performance or system configuration and cannot be reproduced in a test environment.  Furthermore, we are in healthcare so introducing additional software like node.js creates extra work for our security team.  We have to keep the extra technologies to a minimum.  I recommend you consider a simple file logging system like the nlog library. Or just handle the error above an then we would know what the original message was and not need logging…

Thanks for considering my suggestions 😊

Jonathan

Sent from my Windows 10 phone

**Comment by smithrobs** [comment]
Quick clarification re: logging - This .NET lib does not require nodejs for logging; see [the readme logging section](https://github.com/Nexmo/nexmo-dotnet#logging) for details. It makes use of `Microsoft.Extensions.Logging`. You should be able to log to a file instead of the console. I think I have an example around here somewhere - I'll see if I can add that to the readme.

Thanks for the confirmation re: the bug. I will be pushing out a new version in the next 24 hours with fixes for a few separate issues and will include a fix for this one way or another.

**Comment by jonHumphries** [comment]
Oh that’s so awesome, the console solution was driving me nuts.  I’ll get all of this over to Jeff today and have him go through it.  Looking forward to the release 😊

Thanks Rob!!

Sent from Mail for Windows 10

**Comment by smithrobs** [comment]
I'm performing final testing on 2.3.0. Here's what this issue influenced:
- Introduced `Nexmo.Api.EnsureSuccessStatusCode` configuration option. You may instruct the library to throw an exception if a request results in an unsuccessful HTTP status code.
- Expose the configuration `ILoggerFactory` for use with external logging implementations.
- Added file logging example to `Nexmo.Samples.Coverage`

Thanks again for filing the issue, providing feedback, and your patience!

**Comment by jonHumphries** [comment]
Awesome, thank you!

Sent from Mail for Windows 10

**Comment by jonHumphries** [comment]
Hey Rob, still getting the same error on 2.3.  Newtonsoft is unable to deserialize the response on whatever I sent wrong.  I’ll see if I can open the project in VS 2015 now.

Sent from Mail for Windows 10

**Comment by jonHumphries** [comment]
Okay so I had to remove the references to 4.6.2 in order to get it to compile, that’s probably due to something about my VS version and not anything you did wrong.  I also had to remove to missing .config files.  

I added your Nexmo.API project into our solution instead of the dll but for some reason I wasn’t able to figure out, I could add it as a reference but other projects couldn’t see it’s namespaces.  Very weird, I haven’t seen that before. It’s still listed as an xproj so my guess is that has something to do with it.

Just to help trace the missing key error in this library, I’m going to work with your unit test library and try to recreate one of the scenarios.  Stay tuned,.

Sent from Mail for Windows 10

**Comment by smithrobs** [comment]
Is your project a .NET project (not Core)? I can't remember exactly off-hand, but in 2015 referencing one from the other plain doesn't work.

**Comment by jonHumphries** [comment]
Correct we use VS 2015 professional, not core, so it makes sense that we can’t use the raw code then.  You also use nunit, where as we the standard .Net unit test framework so I wasn’t able to trace through the code to find out where error messages were getting caught up; however, I did get the file logging attached which returned this:

2017-11-20T15:08:21.5025108-05:00  [DBG] POST https://api.nexmo.com/v1/calls Nexmo.Api.Voice.Call+CallCommand (e26667f5)
2017-11-20T15:08:21.7815241-05:00  [ERR] FAIL: Unauthorized (8ddea63d)

So basically, you still have a major bug that prevents the user from being able to handle errors when using the .Net client library.   You can recreate it by giving a bogus application id or secret in the one of the files.  If you were to do that and run a test like this:

var command = new Call.CallCommand
            {
                to = new Call.Endpoint[] { new Call.Endpoint { type = "phone", number = "+17148720001" } },
                from = new Call.Endpoint { type = "phone", number = "17144419541" },
                answer_url = new string[] { "dev2.revx.technology:8032/api/v1/nexmo-vapi/vapi-ncco" }
            };

            var actualResult = Nexmo.Api.Voice.Call.Do(command);

Which, instead of repeating “Unauthorized”, it would give you this error message:
Test Name:	PlaceCallTest1
Test FullName:	Nexmo.Api.Test.Integration.VoiceTests.PlaceCallTest1
Test Source:	C:\Users\Jhumphries\Desktop\nexmo-dotnet-master\nexmo-dotnet-master\Nexmo.Api.Test.Integration\VoiceTests.cs : line 19
Test Outcome:	Failed
Test Duration:	0:00:00.7181771

Result StackTrace:	
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Nexmo.Api.Voice.Call.Do(CallCommand cmd, Credentials creds)
   at Nexmo.Api.Test.Integration.VoiceTests.PlaceCallTest1() in C:\Users\Jhumphries\Desktop\nexmo-dotnet-master\nexmo-dotnet-master\Nexmo.Api.Test.Integration\VoiceTests.cs:line 36
Result Message:	
Test method Nexmo.Api.Test.Integration.VoiceTests.PlaceCallTest1 threw exception: 
System.ArgumentNullException: Value cannot be null.
Parameter name: value

Now, we know how to setup the JWT security so if it were just this scenario, it wouldn’t be a big deal; however, this bug hides all errors including some very important ones we still haven’t been able to trace yet (since we can’t see the messages).

Thanks,
Jonathan

Sent from Mail for Windows 10

**Comment by smithrobs** [comment]
Re: the hiding of the exception: Did you set `Nexmo.Api.EnsureSuccessStatusCode` to true? You then should receive a more clear Exception. ("You may instruct the library to throw an exception if a request results in an unsuccessful HTTP status code.")

**Comment by smithrobs** [comment]
v3.0 is out! Please try the release and feel free to reopen this issue if you are still having problems.

**Comment by BloomBitz** [comment]
public ActionResult MakeCall(string to)
        {
            string TO_NUMBER = to;  //indian number along with country code
            string NEXMO_NUMBER = "447949141768"; //it is test number provided in nexmo account

            var results = Client.Call.Do(new Call.CallCommand
            {
                to = new[]
                {
                    new Call.Endpoint {
                        type = "phone",
                        number = TO_NUMBER
                    }
                },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = NEXMO_NUMBER
                },
                answer_url = new[]
                {
                    "https://developer.nexmo.com/ncco/tts.json"
                }
            });

            Session["UUID"] = results.uuid;
            string NEXMO_CALL_UUID = Session["UUID"].ToString();
            string TEXT = "This is a text to speech sample";
            var TTSresult = Client.Call.BeginTalk(NEXMO_CALL_UUID, new Call.TalkCommand
            {
                text = TEXT,
                voice_name = "Kimberly"
            });
            return RedirectToAction("MakeCall"); 
        }


this is my code whenever i am trying to execute this ActionMethod an exception occur "Value cannot be null.Parameter name: value". I did not buy any number. I am using "Test Number" available in  my account of nexmo. Is this thing create this kind of error for voice api in asp.net application. Please suggest me what should i need to do for solving this error.

**Comment by smithrobs** [comment]
@BloomBitz Would you mind either [filing a support request](https://help.nexmo.com/hc/en-us/requests/new) directly to Nexmo or asking in the [Nexmo Slack](https://developer.nexmo.com/community/slack)? This library has no control over the issue if Nexmo does not accept your API calls due to account/billing issues. You will receive a better experience regarding troubleshooting your specific account.

**Comment by BloomBitz** [comment]
Ok thanks

**Comment by BloomBitz** [comment]
my account on Nexmo Slack has been deactivated, I do not know how. Can you
please suggest me hoe to solve the problem that i have been already
mentioned to you

**Comment by BloomBitz** [comment]
I am waiting for last 1hour for the reply of regarding my problem from nexmo support.

**Comment by BloomBitz** [comment]
@smithrobs can you tell me that ncco is a json file actually? If we want to create dynamic ncco for each outbound call it means we need to create json file for each call?
