### ISSUE TITLE
failed to load project on vs2015

### ISSUE THREAD

**Issue by jonHumphries** [Nexmo/nexmo-dotnet#69]
Aloha,
   The downloaded code is xproj type which is not recognized by vs2015 (i'm on professional edition).  It takes a bit of work but i can convert it from xproj to csproj using vs2017; however, thats not a valid edition for our shop yet so we can't use the converted project in vs2015.  I think if you can get it to output a csproj file instead of an xproj file most versions of VS should be able to use it.
Mahalo,
Jonathan

**Comment by smithrobs** [comment]
@jonHumphries We now specify the .NET Core SDK to develop against (v1.0.1, 1.0.0-preview2-003131) in 2015 and everything is working as far as I can tell. When you have a few minutes please try getting latest from master and see if you can compile without issue. The README has been updated with the more specific .NET Core SDK requirements.
