### ISSUE TITLE
Newtonsoft.Json.JsonConvert.DeserializeObject Argument Null exception

### ISSUE THREAD

**Issue by grahambunce** [Nexmo/nexmo-dotnet#71]
Hi

I'm running the 3.0.0 pre3 nuget package. I *think* everything is set up correctly but when I make a Voice call I get a "Argument Null exception" in NewtonSoft. I'm using it in an async pattern and this may be messing up my stack trace, as I don't get any hint as to where this is be thrown.

I think it's in here

```
        public static CallResponse Do(CallCommand cmd, Credentials creds = null)
        {
            var response = VersionedApiRequest.DoRequest("POST", ApiRequest.GetBaseUriFor(typeof(Call), "/v1/calls"), cmd, creds);

            return JsonConvert.DeserializeObject<CallResponse>(response.JsonResponse);
        }
```
as this is the only place in the stack that I can see NewtonSoft being called. This suggests that the response object is null but I can't find out why

**Comment by smithrobs** [comment]
It's _possibly_ because your credentials weren't accepted. You might want to try [logging](https://github.com/Nexmo/nexmo-dotnet#logging) to see if that is the case. I'll still take a look just in case it's something else.

**Comment by billbgarland** [comment]
I am having a similar problem on a Azure platform. Is there a way of confirming the credentials are OK?

On Azure it is not obvious where to save the appsetting.json file. Any suggestions?

**Comment by grahambunce** [comment]
Any update?

Would this be more straightforward if you didn't forcing loading the .key file from disk (i.e. if this is absolutely mandatory, allow it to be embedded or loaded some other way.

As an aside, this new security system is a bit of a pain - an Api Key (such as your main competitor) is much easier to use for a consumer of your service. If you didn't want to use that, than an OpenID Connect based system also works better IMO

**Comment by smithrobs** [comment]
Thanks for your patience - holidays were a bit busy around here. I have a barebones Azure worker role but need to clean up a bit and add it to the examples.

I agree 💯 with better application id/key support - this would be part of #8 - let me see if I can add at least that feature quick and push out a new pre in the next few days.

I personally do not have influence of the architecture of the security system. You can always file a [support request](https://help.nexmo.com/hc/en-us/requests/new) to provide feedback, but it might be more appropriate to chat about it with someone on the [Slack](https://developer.nexmo.com/community/slack).

**Comment by smithrobs** [comment]
v3.0 is out! You can have multiple applications by creating multiple instances of the `Credentials` and `Client` classes.

**Comment by skandyrocks** [comment]
same issue here when I try to transfer a call to a phone number. how did you resolve the issue last time?

**Comment by smithrobs** [comment]
@skandyrocks It is likely a Nexmo authentication issue. You might want to try [logging](https://github.com/Nexmo/nexmo-dotnet#logging) to see if that is the case - you will receive a 401 Unauthorized if your credentials are not accepted or 403 Forbidden if you don't have the ability to perform the operation (e.g. the phone number is not tied to your account/application). You can force the library to throw an exception in these cases with the appconfig setting `Nexmo.Api.EnsureSuccessStatusCode` = `true`.

I have encountered instances in the past where I needed to recreate an older application from scratch to get things working again however I hope that was only a beta-test issue.

Please keep in mind you will receive a better experience by [filing a support request](https://help.nexmo.com/hc/en-us/requests/new) directly to Nexmo or asking in the [Nexmo Slack](https://developer.nexmo.com/community/slack).) I have no control over the issue if Nexmo does not accept your API calls.

**Comment by skandyrocks** [comment]
okay, wanna give you some feedback because I got it to work. I downloaded the repo and modified it because to my mind this library has a problem:
Your destination member in a CallEditCommand is a string. That is kind of a problem because when it comes to a transfer of a call the destination is a complex object. So the json is always malformed when I set the destination (either via a dynamic or my own NexmoDestination-Class that has `public static implicit operator string(NexmoDestination destination)`)
```
{
	"action": "transfer",
	"destination": "{\"type\":\"ncco\",\"url\":[\"https://e2344168.ngrok.io/api/nexmo/handover?callId=1070ceafd03de77feb7c62ffc69af54d&from=4912345678961\"]}"
}
```
what I needed was:
```
{
	"action": "transfer",
	"destination": {
		"type": "ncco",
		"url": ["https://e2344168.ngrok.io/api/nexmo/handover?callId=1070ceafd03de77feb7c62ffc69af54d&from=4912345678961"]
	}
}
```
I think you should change the type of destination from string to a specific Destination-Object because whit the quotes no one can pass a complex object to the destination. Or am I missing something?

**Comment by BloomBitz** [comment]
I am also facing the same problem while adding "Text to Speech" to the existing outbound call. The error i got is described as below:
[ArgumentNullException: Value cannot be null.
Parameter name: value]
   Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) +242
   Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings) +66
   Nexmo.Api.Voice.Call.BeginTalk(String id, TalkCommand cmd, Credentials creds) +103

give me some suggestion

**Comment by ElCompadre** [comment]
I had the same issue, when looking in the debug console I found that the call with Newtonsoft.JsonConvert as a 401 respond, so it was a problem of credentials... And when I got to the Nexmo Slack they told me to create a new application... it fix my problem.

**Comment by slorello89** [comment]
#187 will make this more explicit.

**Comment by slorello89** [comment]
Errors will be much more explicit now in v5.0.0 - we'll make a best-effort to describe the error and we will throw an exception with the error code. Closing this issue out - if anyone continues to encounter these problems please feel free to reopen.
