### ISSUE TITLE
answer_url response chunked response with Kestrel results in NCCO syntax error

### ISSUE THREAD

**Issue by leggetter** [Nexmo/nexmo-dotnet#76]
Note: Not necessarily a nexmo-dotnet issue, but the request here is to reproduce the problem so that it can be escalated to support and engineering:

Kestrel ASP.NET Core seems to be sending the answer URL in a chunked response which the Nexmo platform does not seem to be handling.

Can we reproduce with an example and then escalate?

Apparently related:
https://stackoverflow.com/questions/38085711/invalid-characters-on-response-body

**Comment by smithrobs** [comment]
Was this it? https://twitter.com/jdpearce/status/966415865280315392
