### ISSUE TITLE
{"Value cannot be null." & vbCrLf & "Parameter name: value"}

### ISSUE THREAD

**Issue by digibum** [Nexmo/nexmo-dotnet#77]
I have one app writen in C# Console App and it works.
Now i have created the same app with same credetials only in VB code.
Code looks like this:
`Sub Main()
        Dim _cc As New Nexmo.Api.Voice.Call.CallCommand

        ''Dim _a(0) As Nexmo.Api.Voice.Call.Endpoint

        Dim _to(0) As Nexmo.Api.Voice.Call.Endpoint
        _to(0) = New Nexmo.Api.Voice.Call.Endpoint
        _to(0).type = "phone"
        _to(0).number = "0038631767672"
        ''_a(0) = _to

        Dim _from As New Nexmo.Api.Voice.Call.Endpoint
        _from.type = "phone"
        _from.number = "0038631767672"

        Dim _a2(0) As String
        _a2(0) = "https://gist.github.com/digibum/dc61db514a79c8f4643efc8f88f7b38d/raw/8b1e3501681e2ce1a4aa4d1023a5c91cb5a8636d/alarm3.json"

        _cc.to = _to
        _cc.from = _from
        _cc.answer_url = _a2

        Try
            Dim out = Nexmo.Api.Voice.Call.Do(_cc)
        Catch ex As Exception
            Console.ReadLine()
        End Try
    End Sub`

App.config is same in C# as is in VB app
Error is {"Value cannot be null." & vbCrLf & "Parameter name: value"}

**Comment by smithrobs** [comment]
This will work with v3.0:

```vb
    Sub Main()
        Dim _to(0) As Nexmo.Api.Voice.Call.Endpoint
        _to(0) = New Nexmo.Api.Voice.Call.Endpoint With {
            .type = "phone",
            .number = "15557771212"
        }

        Dim _from As New Nexmo.Api.Voice.Call.Endpoint With {
            .type = "phone",
            .number = "15557771213"
        }

        Dim _a2(0) As String
        _a2(0) = "https://nexmo-community.github.io/ncco-examples/first_call_talk.json"

        Dim _cc As New Nexmo.Api.Voice.Call.CallCommand With {
            .to = _to,
            .from = _from,
            .answer_url = _a2
        }

        Dim _creds As New Nexmo.Api.Request.Credentials With {
            .ApplicationId = "insert your application id (guid) here",
            .ApplicationKey = "-----BEGIN RSA PRIVATE KEY-----
insert your full app key here
-----END RSA PRIVATE KEY-----"
        }

        Dim _client As New Nexmo.Api.Client(_creds)
        Try
            Dim out = _client.Call.Do(_cc)
        Catch ex As Exception
            Console.ReadLine()
        End Try
    End Sub
```

Feel free to reopen/comment if you still have issues.

**Comment by BloomBitz** [comment]
continous error of "value can not be null.Parameter name is value" in asp.net mvc while working with voice api of nexmo. Code is below.
 public ActionResult MakeCall(string to)
        {
            string TO_NUMBER = to;  //Indian mobile number along with country code
            string NEXMO_NUMBER = "447949141768"; //it is test number provided in nexmo account

       
            var results = Client.Call.Do(new Call.CallCommand
            {
                to = new[]
                {
                    new Call.Endpoint {
                        type = "phone",
                        number = TO_NUMBER
                    }
                },
                from = new Call.Endpoint
                {
                    type = "phone",
                    number = NEXMO_NUMBER
                },
                answer_url = new[]
                {
                    "https://developer.nexmo.com/ncco/tts.json"
                }
            });

            Session["UUID"] = results.uuid;
            string NEXMO_CALL_UUID = Session["UUID"].ToString();
            string TEXT = "This is a text to speech sample";
            var TTSresult = Client.Call.BeginTalk(NEXMO_CALL_UUID, new Call.TalkCommand
            {
                text = TEXT,
                voice_name = "Kimberly"
            });

            return RedirectToAction("MakeCall"); 
        }

**Comment by tyronent** [comment]
@RabebOthmani 

I am getting the same error...was there ever a fix or reason for this value cannot be null?

**Comment by AhmedZaza** [comment]
@smithrobs i have the same issue on asp.net core 2 (nexmo website sample code).
why i'm getting this error ?

**Comment by slorello89** [comment]
Hi @AhmedZaza there is some error handling issues that we will be addressing shortly - but the error 'Value Cannot be Null' generally means we got a non-successful response back from the server - in all likelihood I'd guess it's a 401 error can you confirm you're using the appropriate credentials with the client? Feel free to find me in the nexmo community slack if you need help.

**Comment by AhmedZaza** [comment]
@slorello89 okay add me on slack plz.
my slack mail : a.zaza48@yahoo.com
