### ISSUE TITLE
SMS Inbound: message_timestamp parameter is null

### ISSUE THREAD

**Issue by krisnds** [Nexmo/nexmo-dotnet#82]
I have implemented this code in my project (ASP.NET 4.6.1), and all the incoming parameters are brought into the SMS.SMSInbound model except for the message_timestamp.

public ActionResult Get([FromUri]SMS.SMSInbound response)
{
    return new HttpStatusCodeResult(HttpStatusCode.OK);
}

The message_timestamp field is different from the others in that it relies on a JsonProperty to map it to the proper field in the model:
            [JsonProperty("message-timestamp")]
            public string message_timestamp { get; set; }

I tried to build and run the Nexmo.Samples.Web project on my local machine, and needed to install .NET Core 1.0.4 in order to do so. However, the application still does not successfully start and I have not been able to test the web API for an inbound message. I am not able to verify if the message_timestamp gets properly populated in the sample web project.

Any suggestions on how to troubleshoot this?

**Comment by RabebOthmani** [comment]
Hi @krisnds ,
Sorry for not getting back to you any earlier, I've been looking into the problem. 
It seems like a deserialization issue, I'm about to push a fix to solve the problem.

**Comment by smithrobs** [comment]
Fixed in 3.0!

**Comment by krisnds** [comment]
I tried to install the 3.0.0-pre3 release, but got this error:

install-package : Could not install package 'runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0'. You are trying to install this package into a project 
that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, 
contact the package author.
At line:1 char:1
+ install-package nexmo.csharp.client -version 3.0.0-pre3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Is version 3 for .NET Core only?

**Comment by smithrobs** [comment]
Sorry about this - that error is #83. I will be releasing v3.0.0 shortly that will address this.
