### ISSUE TITLE
Unable to install v3 pre-release with a project that targets .Net 4.6.1 

### ISSUE THREAD

**Issue by RabebOthmani** [Nexmo/nexmo-dotnet#83]
![upgrade error](https://user-images.githubusercontent.com/5781590/36308345-2ea12b68-1318-11e8-9242-19c034d605c8.PNG)

**Comment by smithrobs** [comment]
Are you upgrading the project at the same time? Do you have `packages.config`? Might be something related to ```https://github.com/NuGet/Home/issues/4445```

**Comment by RabebOthmani** [comment]
I'm not trying to upgrade the project but i'm definitely getting the same error. yep I have packages.config

**Comment by smithrobs** [comment]
Okay, I can reproduce this... definitely something off with the nuspec...

**Comment by smithrobs** [comment]
This is fixed in v3.0! Thanks for pointing this out.
