### ISSUE TITLE
Support In-App Messaging API

### ISSUE THREAD

**Issue by smithrobs** [Nexmo/nexmo-dotnet#85]
[Docs](https://ea.developer.nexmo.com/conversation/overview)

- [x] Conversations API
- [x] Users API
- [x] Members API

**Comment by smithrobs** [comment]
Stitch is supported in 3.1 thanks to Bibi. Close once 3.1 is out of RC.

**Comment by slorello89** [comment]
In app messaging will not be added to the server SDK - stitch will be added when appropriate.
