### ISSUE TITLE
Managing API throttling (Multiple SMS)

### ISSUE THREAD

**Issue by krisnds** [Nexmo/nexmo-dotnet#87]
I need to send the same message out to a list of phone numbers, and currently I have to put a delay between each message send to avoid getting a throttling status back.

Is there a way to implement the suggested
https://help.nexmo.com/hc/en-us/articles/205065817-How-to-Send-Multiple-SMS-in-a-Single-API-Request

in this dotnet client? Or do you have suggestions as to how to implement this in .NET?

**Comment by smithrobs** [comment]
You can make use of the `Nexmo.Api.RequestsPerSecond` config setting, but that is currently only looked at if you specify it in a `appsettings.json` file.

We should provide better guidance around this - maybe even decouple the `HttpClient` instance from the `Configuration` class (which we are slowly getting away from and moving towards more instance-based usage).

You could also copy [ThrottlingMessageHandler.cs](https://github.com/Nexmo/nexmo-dotnet/blob/df131cce7b3354ec8cf2bd30305339a7afdc6bd7/Nexmo.Api/Request/ThrottlingMessageHandler.cs) and use it yourself with your own `HttpClient`, replacing the `HttpClient` that `Configuration` instantiates.

I'll give this some more thought and try to make some changes/examples after v3.0 is released.

**Comment by slorello89** [comment]
Looks like this was resolved a while ago - going to close this now
