### ISSUE TITLE
System.Security.Cryptography.CryptographicException: 'Bad Data.'

### ISSUE THREAD

**Issue by jsevaj** [Nexmo/nexmo-dotnet#96]
When compiling for .NET 4.5.2 a CryptographicException is thrown with message "Bad Data", when initiating a voice call. When compiling for .NET 4.6 the error does not occur.  I see there is the following comment in the code (in PemParse.cs):

// TODO: throwing "Bad Data" exception even though RSACng is fine

So I guess this is a known issue. However, I was instructed by Nexmo support to formally submit an issue on github.

**Comment by smithrobs** [comment]
Thank you. Yes, this is a bug inside .NET Framework 4.5.2 as far as I can discern. I can find MS support articles describing the issue but no resolution for it. The recommended solution is - unfortunately - to not use 4.5.2 if you require V2 APIs like Application and Call.

If anyone finds a solution for this, feel free to comment/reopen!
