### ISSUE TITLE
App configuration file missing in test project

### ISSUE THREAD

**Issue by parth1729** [Nexmo/nexmo-dotnet#99]
Hi Team , 

We have observed that App.config file in test project is missing. So to run project appopriately it requires searching for all attributes and populate them as part of the new configuration file which is tedious.

Please have this checked in for smooth operation.

**Comment by slorello89** [comment]
There is an appsettings.json.example file for each of the test projects which you would just need to replicate in an appsettings.json file to have the config items set. I think this should resolve the issue so I'm going to close this issue out. If that doesn't solve the problem feel free to reopen and let me know exactly what you need in the app.config. Thanks!
